/* This file is autogenerated, do not edit. */

#include <stubs.h>

int CPAcquireContext()
{
	DbgPrint("WARNING: calling stub CPAcquireContext()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPAcquireContextW()
{
	DbgPrint("WARNING: calling stub CPAcquireContextW()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPCreateHash()
{
	DbgPrint("WARNING: calling stub CPCreateHash()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPDecrypt()
{
	DbgPrint("WARNING: calling stub CPDecrypt()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPDeriveKey()
{
	DbgPrint("WARNING: calling stub CPDeriveKey()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPDestroyHash()
{
	DbgPrint("WARNING: calling stub CPDestroyHash()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPDestroyKey()
{
	DbgPrint("WARNING: calling stub CPDestroyKey()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPEncrypt()
{
	DbgPrint("WARNING: calling stub CPEncrypt()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPExportKey()
{
	DbgPrint("WARNING: calling stub CPExportKey()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPGenKey()
{
	DbgPrint("WARNING: calling stub CPGenKey()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPGenRandom()
{
	DbgPrint("WARNING: calling stub CPGenRandom()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPGetHashParam()
{
	DbgPrint("WARNING: calling stub CPGetHashParam()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPGetKeyParam()
{
	DbgPrint("WARNING: calling stub CPGetKeyParam()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPGetProvParam()
{
	DbgPrint("WARNING: calling stub CPGetProvParam()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPGetUserKey()
{
	DbgPrint("WARNING: calling stub CPGetUserKey()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPHashData()
{
	DbgPrint("WARNING: calling stub CPHashData()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPHashSessionKey()
{
	DbgPrint("WARNING: calling stub CPHashSessionKey()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPImportKey()
{
	DbgPrint("WARNING: calling stub CPImportKey()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPReleaseContext()
{
	DbgPrint("WARNING: calling stub CPReleaseContext()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPSetHashParam()
{
	DbgPrint("WARNING: calling stub CPSetHashParam()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPSetKeyParam()
{
	DbgPrint("WARNING: calling stub CPSetKeyParam()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPSetProvParam()
{
	DbgPrint("WARNING: calling stub CPSetProvParam()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPSignHash()
{
	DbgPrint("WARNING: calling stub CPSignHash()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

int CPVerifySignature()
{
	DbgPrint("WARNING: calling stub CPVerifySignature()\n");
	__wine_spec_unimplemented_stub("sccbase.dll", __FUNCTION__);
	return 0;
}

