/* This file is autogenerated, do not edit. */

#include <stubs.h>

int AccessCheckByTypeResultList()
{
	DbgPrint("WARNING: calling stub AccessCheckByTypeResultList()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CancelOverlappedAccess()
{
	DbgPrint("WARNING: calling stub CancelOverlappedAccess()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CloseCodeAuthzLevel()
{
	DbgPrint("WARNING: calling stub CloseCodeAuthzLevel()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CloseTrace()
{
	DbgPrint("WARNING: calling stub CloseTrace()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ComputeAccessTokenFromCodeAuthzLevel()
{
	DbgPrint("WARNING: calling stub ComputeAccessTokenFromCodeAuthzLevel()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ConvertAccessToSecurityDescriptorA()
{
	DbgPrint("WARNING: calling stub ConvertAccessToSecurityDescriptorA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ConvertAccessToSecurityDescriptorW()
{
	DbgPrint("WARNING: calling stub ConvertAccessToSecurityDescriptorW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ConvertSDToStringSDRootDomainA()
{
	DbgPrint("WARNING: calling stub ConvertSDToStringSDRootDomainA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ConvertSDToStringSDRootDomainW()
{
	DbgPrint("WARNING: calling stub ConvertSDToStringSDRootDomainW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ConvertSecurityDescriptorToAccessA()
{
	DbgPrint("WARNING: calling stub ConvertSecurityDescriptorToAccessA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ConvertSecurityDescriptorToAccessNamedA()
{
	DbgPrint("WARNING: calling stub ConvertSecurityDescriptorToAccessNamedA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ConvertSecurityDescriptorToAccessNamedW()
{
	DbgPrint("WARNING: calling stub ConvertSecurityDescriptorToAccessNamedW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ConvertSecurityDescriptorToAccessW()
{
	DbgPrint("WARNING: calling stub ConvertSecurityDescriptorToAccessW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ConvertStringSDToSDDomainA()
{
	DbgPrint("WARNING: calling stub ConvertStringSDToSDDomainA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ConvertStringSDToSDDomainW()
{
	DbgPrint("WARNING: calling stub ConvertStringSDToSDDomainW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ConvertStringSDToSDRootDomainA()
{
	DbgPrint("WARNING: calling stub ConvertStringSDToSDRootDomainA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ConvertStringSDToSDRootDomainW()
{
	DbgPrint("WARNING: calling stub ConvertStringSDToSDRootDomainW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CreateCodeAuthzLevel()
{
	DbgPrint("WARNING: calling stub CreateCodeAuthzLevel()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CredGetTargetInfoA()
{
	DbgPrint("WARNING: calling stub CredGetTargetInfoA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CredGetTargetInfoW()
{
	DbgPrint("WARNING: calling stub CredGetTargetInfoW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CredProfileLoaded()
{
	DbgPrint("WARNING: calling stub CredProfileLoaded()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CredRenameA()
{
	DbgPrint("WARNING: calling stub CredRenameA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CredRenameW()
{
	DbgPrint("WARNING: calling stub CredRenameW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CredWriteDomainCredentialsW()
{
	DbgPrint("WARNING: calling stub CredWriteDomainCredentialsW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CredpConvertCredential()
{
	DbgPrint("WARNING: calling stub CredpConvertCredential()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CredpConvertTargetInfo()
{
	DbgPrint("WARNING: calling stub CredpConvertTargetInfo()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CredpDecodeCredential()
{
	DbgPrint("WARNING: calling stub CredpDecodeCredential()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int CredpEncodeCredential()
{
	DbgPrint("WARNING: calling stub CredpEncodeCredential()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int DuplicateEncryptionInfoFile()
{
	DbgPrint("WARNING: calling stub DuplicateEncryptionInfoFile()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int EncryptedFileKeyInfo()
{
	DbgPrint("WARNING: calling stub EncryptedFileKeyInfo()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int FreeEncryptedFileKeyInfo()
{
	DbgPrint("WARNING: calling stub FreeEncryptedFileKeyInfo()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int GetAccessPermissionsForObjectA()
{
	DbgPrint("WARNING: calling stub GetAccessPermissionsForObjectA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int GetAccessPermissionsForObjectW()
{
	DbgPrint("WARNING: calling stub GetAccessPermissionsForObjectW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int GetInformationCodeAuthzLevelW()
{
	DbgPrint("WARNING: calling stub GetInformationCodeAuthzLevelW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int GetInformationCodeAuthzPolicyW()
{
	DbgPrint("WARNING: calling stub GetInformationCodeAuthzPolicyW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int GetLocalManagedApplicationData()
{
	DbgPrint("WARNING: calling stub GetLocalManagedApplicationData()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int GetLocalManagedApplications()
{
	DbgPrint("WARNING: calling stub GetLocalManagedApplications()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int GetManagedApplicationCategories()
{
	DbgPrint("WARNING: calling stub GetManagedApplicationCategories()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int GetManagedApplications()
{
	DbgPrint("WARNING: calling stub GetManagedApplications()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int GetNamedSecurityInfoExA()
{
	DbgPrint("WARNING: calling stub GetNamedSecurityInfoExA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int GetNamedSecurityInfoExW()
{
	DbgPrint("WARNING: calling stub GetNamedSecurityInfoExW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int GetOverlappedAccessResults()
{
	DbgPrint("WARNING: calling stub GetOverlappedAccessResults()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int I_QueryTagInformation()
{
	DbgPrint("WARNING: calling stub I_QueryTagInformation()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int I_ScSendTSMessage()
{
	DbgPrint("WARNING: calling stub I_ScSendTSMessage()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int IdentifyCodeAuthzLevelW()
{
	DbgPrint("WARNING: calling stub IdentifyCodeAuthzLevelW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int InstallApplication()
{
	DbgPrint("WARNING: calling stub InstallApplication()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int IsTokenUntrusted()
{
	DbgPrint("WARNING: calling stub IsTokenUntrusted()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int LookupSecurityDescriptorPartsA()
{
	DbgPrint("WARNING: calling stub LookupSecurityDescriptorPartsA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int LookupSecurityDescriptorPartsW()
{
	DbgPrint("WARNING: calling stub LookupSecurityDescriptorPartsW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int LsaICLookupNames()
{
	DbgPrint("WARNING: calling stub LsaICLookupNames()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int LsaICLookupNamesWithCreds()
{
	DbgPrint("WARNING: calling stub LsaICLookupNamesWithCreds()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int LsaICLookupSids()
{
	DbgPrint("WARNING: calling stub LsaICLookupSids()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int LsaICLookupSidsWithCreds()
{
	DbgPrint("WARNING: calling stub LsaICLookupSidsWithCreds()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int MSChapSrvChangePassword2()
{
	DbgPrint("WARNING: calling stub MSChapSrvChangePassword2()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int MSChapSrvChangePassword()
{
	DbgPrint("WARNING: calling stub MSChapSrvChangePassword()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int OpenEncryptedFileRawA()
{
	DbgPrint("WARNING: calling stub OpenEncryptedFileRawA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int OpenEncryptedFileRawW()
{
	DbgPrint("WARNING: calling stub OpenEncryptedFileRawW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int OpenTraceA()
{
	DbgPrint("WARNING: calling stub OpenTraceA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int OpenTraceW()
{
	DbgPrint("WARNING: calling stub OpenTraceW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ProcessIdleTasks()
{
	DbgPrint("WARNING: calling stub ProcessIdleTasks()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ProcessTrace()
{
	DbgPrint("WARNING: calling stub ProcessTrace()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int ReadEncryptedFileRaw()
{
	DbgPrint("WARNING: calling stub ReadEncryptedFileRaw()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int RegConnectRegistryExA()
{
	DbgPrint("WARNING: calling stub RegConnectRegistryExA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int RegConnectRegistryExW()
{
	DbgPrint("WARNING: calling stub RegConnectRegistryExW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int RegisterIdleTask()
{
	DbgPrint("WARNING: calling stub RegisterIdleTask()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int RemoveTraceCallback()
{
	DbgPrint("WARNING: calling stub RemoveTraceCallback()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SaferGetLevelInformation()
{
	DbgPrint("WARNING: calling stub SaferGetLevelInformation()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SaferSetLevelInformation()
{
	DbgPrint("WARNING: calling stub SaferSetLevelInformation()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SaferSetPolicyInformation()
{
	DbgPrint("WARNING: calling stub SaferSetPolicyInformation()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SaferiChangeRegistryScope()
{
	DbgPrint("WARNING: calling stub SaferiChangeRegistryScope()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SaferiCompareTokenLevels()
{
	DbgPrint("WARNING: calling stub SaferiCompareTokenLevels()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SaferiIsExecutableFileType()
{
	DbgPrint("WARNING: calling stub SaferiIsExecutableFileType()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SaferiPopulateDefaultsInRegistry()
{
	DbgPrint("WARNING: calling stub SaferiPopulateDefaultsInRegistry()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SaferiRecordEventLogEntry()
{
	DbgPrint("WARNING: calling stub SaferiRecordEventLogEntry()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SaferiReplaceProcessThreadTokens()
{
	DbgPrint("WARNING: calling stub SaferiReplaceProcessThreadTokens()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SaferiSearchMatchingHashRules()
{
	DbgPrint("WARNING: calling stub SaferiSearchMatchingHashRules()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SetEntriesInAccessListA()
{
	DbgPrint("WARNING: calling stub SetEntriesInAccessListA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SetEntriesInAccessListW()
{
	DbgPrint("WARNING: calling stub SetEntriesInAccessListW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SetEntriesInAuditListA()
{
	DbgPrint("WARNING: calling stub SetEntriesInAuditListA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SetEntriesInAuditListW()
{
	DbgPrint("WARNING: calling stub SetEntriesInAuditListW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SetInformationCodeAuthzLevelW()
{
	DbgPrint("WARNING: calling stub SetInformationCodeAuthzLevelW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SetInformationCodeAuthzPolicyW()
{
	DbgPrint("WARNING: calling stub SetInformationCodeAuthzPolicyW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SetNamedSecurityInfoExA()
{
	DbgPrint("WARNING: calling stub SetNamedSecurityInfoExA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SetNamedSecurityInfoExW()
{
	DbgPrint("WARNING: calling stub SetNamedSecurityInfoExW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SetPrivateObjectSecurityEx()
{
	DbgPrint("WARNING: calling stub SetPrivateObjectSecurityEx()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SetSecurityInfoExA()
{
	DbgPrint("WARNING: calling stub SetSecurityInfoExA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SetSecurityInfoExW()
{
	DbgPrint("WARNING: calling stub SetSecurityInfoExW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SetTraceCallback()
{
	DbgPrint("WARNING: calling stub SetTraceCallback()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int SetUserFileEncryptionKey()
{
	DbgPrint("WARNING: calling stub SetUserFileEncryptionKey()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int TrusteeAccessToObjectA()
{
	DbgPrint("WARNING: calling stub TrusteeAccessToObjectA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int TrusteeAccessToObjectW()
{
	DbgPrint("WARNING: calling stub TrusteeAccessToObjectW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int UninstallApplication()
{
	DbgPrint("WARNING: calling stub UninstallApplication()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int UnregisterIdleTask()
{
	DbgPrint("WARNING: calling stub UnregisterIdleTask()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WdmWmiServiceMain()
{
	DbgPrint("WARNING: calling stub WdmWmiServiceMain()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiCloseBlock()
{
	DbgPrint("WARNING: calling stub WmiCloseBlock()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiCloseTraceWithCursor()
{
	DbgPrint("WARNING: calling stub WmiCloseTraceWithCursor()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiConvertTimestamp()
{
	DbgPrint("WARNING: calling stub WmiConvertTimestamp()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiDevInstToInstanceNameA()
{
	DbgPrint("WARNING: calling stub WmiDevInstToInstanceNameA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiDevInstToInstanceNameW()
{
	DbgPrint("WARNING: calling stub WmiDevInstToInstanceNameW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiEnumerateGuids()
{
	DbgPrint("WARNING: calling stub WmiEnumerateGuids()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiExecuteMethodA()
{
	DbgPrint("WARNING: calling stub WmiExecuteMethodA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiExecuteMethodW()
{
	DbgPrint("WARNING: calling stub WmiExecuteMethodW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiFileHandleToInstanceNameA()
{
	DbgPrint("WARNING: calling stub WmiFileHandleToInstanceNameA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiFileHandleToInstanceNameW()
{
	DbgPrint("WARNING: calling stub WmiFileHandleToInstanceNameW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiFreeBuffer()
{
	DbgPrint("WARNING: calling stub WmiFreeBuffer()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiGetFirstTraceOffset()
{
	DbgPrint("WARNING: calling stub WmiGetFirstTraceOffset()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiGetNextEvent()
{
	DbgPrint("WARNING: calling stub WmiGetNextEvent()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiGetTraceHeader()
{
	DbgPrint("WARNING: calling stub WmiGetTraceHeader()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiMofEnumerateResourcesA()
{
	DbgPrint("WARNING: calling stub WmiMofEnumerateResourcesA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiMofEnumerateResourcesW()
{
	DbgPrint("WARNING: calling stub WmiMofEnumerateResourcesW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiOpenBlock()
{
	DbgPrint("WARNING: calling stub WmiOpenBlock()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiOpenTraceWithCursor()
{
	DbgPrint("WARNING: calling stub WmiOpenTraceWithCursor()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiParseTraceEvent()
{
	DbgPrint("WARNING: calling stub WmiParseTraceEvent()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiQueryAllDataA()
{
	DbgPrint("WARNING: calling stub WmiQueryAllDataA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiQueryAllDataMultipleA()
{
	DbgPrint("WARNING: calling stub WmiQueryAllDataMultipleA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiQueryAllDataMultipleW()
{
	DbgPrint("WARNING: calling stub WmiQueryAllDataMultipleW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiQueryAllDataW()
{
	DbgPrint("WARNING: calling stub WmiQueryAllDataW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiQueryGuidInformation()
{
	DbgPrint("WARNING: calling stub WmiQueryGuidInformation()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiQuerySingleInstanceA()
{
	DbgPrint("WARNING: calling stub WmiQuerySingleInstanceA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiQuerySingleInstanceMultipleA()
{
	DbgPrint("WARNING: calling stub WmiQuerySingleInstanceMultipleA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiQuerySingleInstanceMultipleW()
{
	DbgPrint("WARNING: calling stub WmiQuerySingleInstanceMultipleW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiQuerySingleInstanceW()
{
	DbgPrint("WARNING: calling stub WmiQuerySingleInstanceW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiSetSingleInstanceA()
{
	DbgPrint("WARNING: calling stub WmiSetSingleInstanceA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiSetSingleInstanceW()
{
	DbgPrint("WARNING: calling stub WmiSetSingleInstanceW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiSetSingleItemA()
{
	DbgPrint("WARNING: calling stub WmiSetSingleItemA()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int WmiSetSingleItemW()
{
	DbgPrint("WARNING: calling stub WmiSetSingleItemW()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

int Wow64Win32ApiEntry()
{
	DbgPrint("WARNING: calling stub Wow64Win32ApiEntry()\n");
	__wine_spec_unimplemented_stub("advapi32.dll", __FUNCTION__);
	return 0;
}

