/* This file is autogenerated, do not edit. */

#include <stubs.h>

int CertDllVerifyCTLUsage()
{
	DbgPrint("WARNING: calling stub CertDllVerifyCTLUsage()\n");
	__wine_spec_unimplemented_stub("cryptnet.dll", __FUNCTION__);
	return 0;
}

int CryptnetWlxLogoffEvent()
{
	DbgPrint("WARNING: calling stub CryptnetWlxLogoffEvent()\n");
	__wine_spec_unimplemented_stub("cryptnet.dll", __FUNCTION__);
	return 0;
}

int LdapProvOpenStore()
{
	DbgPrint("WARNING: calling stub LdapProvOpenStore()\n");
	__wine_spec_unimplemented_stub("cryptnet.dll", __FUNCTION__);
	return 0;
}

int CryptCancelAsyncRetrieval()
{
	DbgPrint("WARNING: calling stub CryptCancelAsyncRetrieval()\n");
	__wine_spec_unimplemented_stub("cryptnet.dll", __FUNCTION__);
	return 0;
}

int CryptFlushTimeValidObject()
{
	DbgPrint("WARNING: calling stub CryptFlushTimeValidObject()\n");
	__wine_spec_unimplemented_stub("cryptnet.dll", __FUNCTION__);
	return 0;
}

int CryptGetTimeValidObject()
{
	DbgPrint("WARNING: calling stub CryptGetTimeValidObject()\n");
	__wine_spec_unimplemented_stub("cryptnet.dll", __FUNCTION__);
	return 0;
}

int CryptInstallCancelRetrieval()
{
	DbgPrint("WARNING: calling stub CryptInstallCancelRetrieval()\n");
	__wine_spec_unimplemented_stub("cryptnet.dll", __FUNCTION__);
	return 0;
}

int CryptUninstallCancelRetrieval()
{
	DbgPrint("WARNING: calling stub CryptUninstallCancelRetrieval()\n");
	__wine_spec_unimplemented_stub("cryptnet.dll", __FUNCTION__);
	return 0;
}

int I_CryptNetEnumUrlCacheEntry()
{
	DbgPrint("WARNING: calling stub I_CryptNetEnumUrlCacheEntry()\n");
	__wine_spec_unimplemented_stub("cryptnet.dll", __FUNCTION__);
	return 0;
}

int I_CryptNetGetHostNameFromUrl()
{
	DbgPrint("WARNING: calling stub I_CryptNetGetHostNameFromUrl()\n");
	__wine_spec_unimplemented_stub("cryptnet.dll", __FUNCTION__);
	return 0;
}

int I_CryptNetGetUserDsStoreUrl()
{
	DbgPrint("WARNING: calling stub I_CryptNetGetUserDsStoreUrl()\n");
	__wine_spec_unimplemented_stub("cryptnet.dll", __FUNCTION__);
	return 0;
}

int I_CryptNetIsConnected()
{
	DbgPrint("WARNING: calling stub I_CryptNetIsConnected()\n");
	__wine_spec_unimplemented_stub("cryptnet.dll", __FUNCTION__);
	return 0;
}

