/*** Autogenerated by WIDL <undefined version> - Do not edit ***/

#ifdef __REACTOS__
#define WIN32_NO_STATUS
#define WIN32_LEAN_AND_MEAN
#endif

#include <objbase.h>
#include <rpcproxy.h>

#ifdef __cplusplus
extern "C" {
#endif

EXTERN_PROXY_FILE(dcom)
EXTERN_PROXY_FILE(ole32_unknwn)
EXTERN_PROXY_FILE(ole32_objidl)
EXTERN_PROXY_FILE(ole32_oleidl)

PROXYFILE_LIST_START
/* Start of list */
  REFERENCE_PROXY_FILE(dcom),
  REFERENCE_PROXY_FILE(ole32_unknwn),
  REFERENCE_PROXY_FILE(ole32_objidl),
  REFERENCE_PROXY_FILE(ole32_oleidl),
/* End of list */
PROXYFILE_LIST_END

DLLDATA_ROUTINES(aProxyFileList, GET_DLL_CLSID)

#ifdef __cplusplus
}
#endif

