/* This file is autogenerated, do not edit. */

#include <stubs.h>

int Control_RunDLLNoFallback()
{
	DbgPrint("WARNING: calling stub Control_RunDLLNoFallback()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int DDEHandleViewFolderNotify()
{
	DbgPrint("WARNING: calling stub DDEHandleViewFolderNotify()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHInvokePrivilegedFunctionW()
{
	DbgPrint("WARNING: calling stub SHInvokePrivilegedFunctionW()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHGetActiveConsoleSessionId()
{
	DbgPrint("WARNING: calling stub SHGetActiveConsoleSessionId()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHIsCurrentProcessConsoleSession()
{
	DbgPrint("WARNING: calling stub SHIsCurrentProcessConsoleSession()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int DisconnectWindowsDialog()
{
	DbgPrint("WARNING: calling stub DisconnectWindowsDialog()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHCreateLocalServerRunDll()
{
	DbgPrint("WARNING: calling stub SHCreateLocalServerRunDll()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHEnableServiceObject()
{
	DbgPrint("WARNING: calling stub SHEnableServiceObject()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHStgOpenStorageW()
{
	DbgPrint("WARNING: calling stub SHStgOpenStorageW()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHStgOpenStorageA()
{
	DbgPrint("WARNING: calling stub SHStgOpenStorageA()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHIsLegacyAnsiProperty()
{
	DbgPrint("WARNING: calling stub SHIsLegacyAnsiProperty()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHFileSysBindToStorage()
{
	DbgPrint("WARNING: calling stub SHFileSysBindToStorage()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHCreateInstance()
{
	DbgPrint("WARNING: calling stub SHCreateInstance()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int __stdcall SHRegisterDarwinLink(long a0, long a1, long a2)
{
	DbgPrint("WARNING: calling stub SHRegisterDarwinLink(0x%lx,0x%lx,0x%lx)\n", (long)a0, (long)a1, (long)a2);
	return 0;
}

int SHCreateFileDataObject()
{
	DbgPrint("WARNING: calling stub SHCreateFileDataObject()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int Create_IEnumUICommand()
{
	DbgPrint("WARNING: calling stub Create_IEnumUICommand()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int Create_IUIElement()
{
	DbgPrint("WARNING: calling stub Create_IUIElement()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHGetShellStyleHInstance()
{
	DbgPrint("WARNING: calling stub SHGetShellStyleHInstance()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHGetAttributesFromDataObject()
{
	DbgPrint("WARNING: calling stub SHGetAttributesFromDataObject()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHSimulateDropOnClsid()
{
	DbgPrint("WARNING: calling stub SHSimulateDropOnClsid()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int SHLimitInputEditWithFlags()
{
	DbgPrint("WARNING: calling stub SHLimitInputEditWithFlags()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

int DeleteFileThumbnail()
{
	DbgPrint("WARNING: calling stub DeleteFileThumbnail()\n");
	__wine_spec_unimplemented_stub("shell32.dll", __FUNCTION__);
	return 0;
}

