/* This file is autogenerated, do not edit. */

#include <stubs.h>

int GetTapi16CallbackMsg()
{
	DbgPrint("WARNING: calling stub GetTapi16CallbackMsg()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int LAddrParamsInited()
{
	DbgPrint("WARNING: calling stub LAddrParamsInited()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int LOpenDialAsst()
{
	DbgPrint("WARNING: calling stub LOpenDialAsst()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int LocWizardDlgProc()
{
	DbgPrint("WARNING: calling stub LocWizardDlgProc()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCAddProvider()
{
	DbgPrint("WARNING: calling stub MMCAddProvider()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCConfigProvider()
{
	DbgPrint("WARNING: calling stub MMCConfigProvider()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCGetAvailableProviders()
{
	DbgPrint("WARNING: calling stub MMCGetAvailableProviders()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCGetDeviceFlags()
{
	DbgPrint("WARNING: calling stub MMCGetDeviceFlags()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCGetLineInfo()
{
	DbgPrint("WARNING: calling stub MMCGetLineInfo()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCGetLineStatus()
{
	DbgPrint("WARNING: calling stub MMCGetLineStatus()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCGetPhoneInfo()
{
	DbgPrint("WARNING: calling stub MMCGetPhoneInfo()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCGetPhoneStatus()
{
	DbgPrint("WARNING: calling stub MMCGetPhoneStatus()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCGetProviderList()
{
	DbgPrint("WARNING: calling stub MMCGetProviderList()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCGetServerConfig()
{
	DbgPrint("WARNING: calling stub MMCGetServerConfig()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCInitialize()
{
	DbgPrint("WARNING: calling stub MMCInitialize()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCRemoveProvider()
{
	DbgPrint("WARNING: calling stub MMCRemoveProvider()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCSetLineInfo()
{
	DbgPrint("WARNING: calling stub MMCSetLineInfo()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCSetPhoneInfo()
{
	DbgPrint("WARNING: calling stub MMCSetPhoneInfo()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCSetServerConfig()
{
	DbgPrint("WARNING: calling stub MMCSetServerConfig()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int MMCShutdown()
{
	DbgPrint("WARNING: calling stub MMCShutdown()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int NonAsyncEventThread()
{
	DbgPrint("WARNING: calling stub NonAsyncEventThread()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int TAPIWndProc()
{
	DbgPrint("WARNING: calling stub TAPIWndProc()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int TUISPIDLLCallback()
{
	DbgPrint("WARNING: calling stub TUISPIDLLCallback()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int internalCreateDefLocation()
{
	DbgPrint("WARNING: calling stub internalCreateDefLocation()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int internalPerformance()
{
	DbgPrint("WARNING: calling stub internalPerformance()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineAgentSpecific()
{
	DbgPrint("WARNING: calling stub lineAgentSpecific()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineBlindTransferW()
{
	DbgPrint("WARNING: calling stub lineBlindTransferW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineConfigDialogEditW()
{
	DbgPrint("WARNING: calling stub lineConfigDialogEditW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineCreateAgentA()
{
	DbgPrint("WARNING: calling stub lineCreateAgentA()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineCreateAgentSessionA()
{
	DbgPrint("WARNING: calling stub lineCreateAgentSessionA()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineCreateAgentSessionW()
{
	DbgPrint("WARNING: calling stub lineCreateAgentSessionW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineCreateAgentW()
{
	DbgPrint("WARNING: calling stub lineCreateAgentW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineForwardW()
{
	DbgPrint("WARNING: calling stub lineForwardW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGatherDigitsW()
{
	DbgPrint("WARNING: calling stub lineGatherDigitsW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGenerateDigitsW()
{
	DbgPrint("WARNING: calling stub lineGenerateDigitsW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAddressCapsW()
{
	DbgPrint("WARNING: calling stub lineGetAddressCapsW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAddressIDW()
{
	DbgPrint("WARNING: calling stub lineGetAddressIDW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAddressStatusW()
{
	DbgPrint("WARNING: calling stub lineGetAddressStatusW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAgentActivityListA()
{
	DbgPrint("WARNING: calling stub lineGetAgentActivityListA()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAgentActivityListW()
{
	DbgPrint("WARNING: calling stub lineGetAgentActivityListW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAgentCapsA()
{
	DbgPrint("WARNING: calling stub lineGetAgentCapsA()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAgentCapsW()
{
	DbgPrint("WARNING: calling stub lineGetAgentCapsW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAgentGroupListA()
{
	DbgPrint("WARNING: calling stub lineGetAgentGroupListA()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAgentGroupListW()
{
	DbgPrint("WARNING: calling stub lineGetAgentGroupListW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAgentInfo()
{
	DbgPrint("WARNING: calling stub lineGetAgentInfo()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAgentSessionInfo()
{
	DbgPrint("WARNING: calling stub lineGetAgentSessionInfo()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAgentSessionList()
{
	DbgPrint("WARNING: calling stub lineGetAgentSessionList()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAgentStatusA()
{
	DbgPrint("WARNING: calling stub lineGetAgentStatusA()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAgentStatusW()
{
	DbgPrint("WARNING: calling stub lineGetAgentStatusW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetAppPriorityW()
{
	DbgPrint("WARNING: calling stub lineGetAppPriorityW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetCallInfoW()
{
	DbgPrint("WARNING: calling stub lineGetCallInfoW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetDevConfigW()
{
	DbgPrint("WARNING: calling stub lineGetDevConfigW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetGroupListA()
{
	DbgPrint("WARNING: calling stub lineGetGroupListA()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetGroupListW()
{
	DbgPrint("WARNING: calling stub lineGetGroupListW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetIconW()
{
	DbgPrint("WARNING: calling stub lineGetIconW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetLineDevStatusW()
{
	DbgPrint("WARNING: calling stub lineGetLineDevStatusW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetProxyStatus()
{
	DbgPrint("WARNING: calling stub lineGetProxyStatus()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetQueueInfo()
{
	DbgPrint("WARNING: calling stub lineGetQueueInfo()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetQueueInfoA()
{
	DbgPrint("WARNING: calling stub lineGetQueueInfoA()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetQueueInfoW()
{
	DbgPrint("WARNING: calling stub lineGetQueueInfoW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetRequestW()
{
	DbgPrint("WARNING: calling stub lineGetRequestW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineGetTranslateCapsW()
{
	DbgPrint("WARNING: calling stub lineGetTranslateCapsW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineHandoffW()
{
	DbgPrint("WARNING: calling stub lineHandoffW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineParkW()
{
	DbgPrint("WARNING: calling stub lineParkW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int linePickupW()
{
	DbgPrint("WARNING: calling stub linePickupW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int linePrepareAddToConferenceW()
{
	DbgPrint("WARNING: calling stub linePrepareAddToConferenceW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineProxyMessage()
{
	DbgPrint("WARNING: calling stub lineProxyMessage()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineProxyResponse()
{
	DbgPrint("WARNING: calling stub lineProxyResponse()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineRedirectW()
{
	DbgPrint("WARNING: calling stub lineRedirectW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetAgentActivity()
{
	DbgPrint("WARNING: calling stub lineSetAgentActivity()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetAgentGroup()
{
	DbgPrint("WARNING: calling stub lineSetAgentGroup()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetAgentMeasurementPeriod()
{
	DbgPrint("WARNING: calling stub lineSetAgentMeasurementPeriod()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetAgentSessionState()
{
	DbgPrint("WARNING: calling stub lineSetAgentSessionState()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetAgentState()
{
	DbgPrint("WARNING: calling stub lineSetAgentState()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetAgentStateEx()
{
	DbgPrint("WARNING: calling stub lineSetAgentStateEx()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetAppPriorityW()
{
	DbgPrint("WARNING: calling stub lineSetAppPriorityW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetCallData()
{
	DbgPrint("WARNING: calling stub lineSetCallData()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetCallQualityOfService()
{
	DbgPrint("WARNING: calling stub lineSetCallQualityOfService()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetCallTreatment()
{
	DbgPrint("WARNING: calling stub lineSetCallTreatment()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetDevConfigW()
{
	DbgPrint("WARNING: calling stub lineSetDevConfigW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetLineDevStatus()
{
	DbgPrint("WARNING: calling stub lineSetLineDevStatus()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetQueueMeasurementPeriod()
{
	DbgPrint("WARNING: calling stub lineSetQueueMeasurementPeriod()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetTollListW()
{
	DbgPrint("WARNING: calling stub lineSetTollListW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetupConferenceW()
{
	DbgPrint("WARNING: calling stub lineSetupConferenceW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineSetupTransferW()
{
	DbgPrint("WARNING: calling stub lineSetupTransferW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int lineUnparkW()
{
	DbgPrint("WARNING: calling stub lineUnparkW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int phoneConfigDialogW()
{
	DbgPrint("WARNING: calling stub phoneConfigDialogW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int phoneGetButtonInfoW()
{
	DbgPrint("WARNING: calling stub phoneGetButtonInfoW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int phoneGetDevCapsW()
{
	DbgPrint("WARNING: calling stub phoneGetDevCapsW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int phoneGetIDW()
{
	DbgPrint("WARNING: calling stub phoneGetIDW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int phoneGetIconW()
{
	DbgPrint("WARNING: calling stub phoneGetIconW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int phoneGetStatusW()
{
	DbgPrint("WARNING: calling stub phoneGetStatusW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int phoneSetButtonInfoW()
{
	DbgPrint("WARNING: calling stub phoneSetButtonInfoW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int tapiRequestDrop()
{
	DbgPrint("WARNING: calling stub tapiRequestDrop()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int tapiRequestMakeCallW()
{
	DbgPrint("WARNING: calling stub tapiRequestMakeCallW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int tapiRequestMediaCall()
{
	DbgPrint("WARNING: calling stub tapiRequestMediaCall()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int tapiRequestMediaCallA()
{
	DbgPrint("WARNING: calling stub tapiRequestMediaCallA()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

int tapiRequestMediaCallW()
{
	DbgPrint("WARNING: calling stub tapiRequestMediaCallW()\n");
	__wine_spec_unimplemented_stub("tapi32.dll", __FUNCTION__);
	return 0;
}

