/* This file is autogenerated, do not edit. */

#include <stubs.h>

int SnmpMgrClose()
{
	DbgPrint("WARNING: calling stub SnmpMgrClose()\n");
	__wine_spec_unimplemented_stub("mgmtapi.dll", __FUNCTION__);
	return 0;
}

int SnmpMgrCtl()
{
	DbgPrint("WARNING: calling stub SnmpMgrCtl()\n");
	__wine_spec_unimplemented_stub("mgmtapi.dll", __FUNCTION__);
	return 0;
}

int SnmpMgrGetTrap()
{
	DbgPrint("WARNING: calling stub SnmpMgrGetTrap()\n");
	__wine_spec_unimplemented_stub("mgmtapi.dll", __FUNCTION__);
	return 0;
}

int SnmpMgrGetTrapEx()
{
	DbgPrint("WARNING: calling stub SnmpMgrGetTrapEx()\n");
	__wine_spec_unimplemented_stub("mgmtapi.dll", __FUNCTION__);
	return 0;
}

int SnmpMgrOidToStr()
{
	DbgPrint("WARNING: calling stub SnmpMgrOidToStr()\n");
	__wine_spec_unimplemented_stub("mgmtapi.dll", __FUNCTION__);
	return 0;
}

int SnmpMgrOpen()
{
	DbgPrint("WARNING: calling stub SnmpMgrOpen()\n");
	__wine_spec_unimplemented_stub("mgmtapi.dll", __FUNCTION__);
	return 0;
}

int SnmpMgrRequest()
{
	DbgPrint("WARNING: calling stub SnmpMgrRequest()\n");
	__wine_spec_unimplemented_stub("mgmtapi.dll", __FUNCTION__);
	return 0;
}

int SnmpMgrStrToOid()
{
	DbgPrint("WARNING: calling stub SnmpMgrStrToOid()\n");
	__wine_spec_unimplemented_stub("mgmtapi.dll", __FUNCTION__);
	return 0;
}

