/* This file is autogenerated, do not edit. */

#include <stubs.h>

int LPSAFEARRAY_Size()
{
	DbgPrint("WARNING: calling stub LPSAFEARRAY_Size()\n");
	__wine_spec_unimplemented_stub("oleaut32.dll", __FUNCTION__);
	return 0;
}

int LPSAFEARRAY_Marshal()
{
	DbgPrint("WARNING: calling stub LPSAFEARRAY_Marshal()\n");
	__wine_spec_unimplemented_stub("oleaut32.dll", __FUNCTION__);
	return 0;
}

int LPSAFEARRAY_Unmarshal()
{
	DbgPrint("WARNING: calling stub LPSAFEARRAY_Unmarshal()\n");
	__wine_spec_unimplemented_stub("oleaut32.dll", __FUNCTION__);
	return 0;
}

int OACreateTypeLib2()
{
	DbgPrint("WARNING: calling stub OACreateTypeLib2()\n");
	__wine_spec_unimplemented_stub("oleaut32.dll", __FUNCTION__);
	return 0;
}

int SetVarConversionLocaleSetting()
{
	DbgPrint("WARNING: calling stub SetVarConversionLocaleSetting()\n");
	__wine_spec_unimplemented_stub("oleaut32.dll", __FUNCTION__);
	return 0;
}

int GetVarConversionLocaleSetting()
{
	DbgPrint("WARNING: calling stub GetVarConversionLocaleSetting()\n");
	__wine_spec_unimplemented_stub("oleaut32.dll", __FUNCTION__);
	return 0;
}

int OleLoadPictureFileEx()
{
	DbgPrint("WARNING: calling stub OleLoadPictureFileEx()\n");
	__wine_spec_unimplemented_stub("oleaut32.dll", __FUNCTION__);
	return 0;
}

