/* This file is autogenerated, do not edit. */

#include <stubs.h>

int AbortPrinter()
{
	DbgPrint("WARNING: calling stub AbortPrinter()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AddDriverCatalog()
{
	DbgPrint("WARNING: calling stub AddDriverCatalog()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AddFormW()
{
	DbgPrint("WARNING: calling stub AddFormW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AddMonitorW()
{
	DbgPrint("WARNING: calling stub AddMonitorW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AddPerMachineConnectionW()
{
	DbgPrint("WARNING: calling stub AddPerMachineConnectionW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AddPortExW()
{
	DbgPrint("WARNING: calling stub AddPortExW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AddPortW()
{
	DbgPrint("WARNING: calling stub AddPortW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AddPrinterConnectionW()
{
	DbgPrint("WARNING: calling stub AddPrinterConnectionW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AddPrinterDriverExW()
{
	DbgPrint("WARNING: calling stub AddPrinterDriverExW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AddPrinterDriverW()
{
	DbgPrint("WARNING: calling stub AddPrinterDriverW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AddPrinterExW()
{
	DbgPrint("WARNING: calling stub AddPrinterExW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AddPrinterW()
{
	DbgPrint("WARNING: calling stub AddPrinterW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AddPrintProcessorW()
{
	DbgPrint("WARNING: calling stub AddPrintProcessorW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AddPrintProvidorW()
{
	DbgPrint("WARNING: calling stub AddPrintProvidorW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AdjustPointers()
{
	DbgPrint("WARNING: calling stub AdjustPointers()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AdjustPointersInStructuresArray()
{
	DbgPrint("WARNING: calling stub AdjustPointersInStructuresArray()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AlignKMPtr()
{
	DbgPrint("WARNING: calling stub AlignKMPtr()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AllowRemoteCalls()
{
	DbgPrint("WARNING: calling stub AllowRemoteCalls()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int AppendPrinterNotifyInfoData()
{
	DbgPrint("WARNING: calling stub AppendPrinterNotifyInfoData()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int bGetDevModePerUser()
{
	DbgPrint("WARNING: calling stub bGetDevModePerUser()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int bSetDevModePerUser()
{
	DbgPrint("WARNING: calling stub bSetDevModePerUser()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int CacheAddName()
{
	DbgPrint("WARNING: calling stub CacheAddName()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int CacheCreateAndAddNode()
{
	DbgPrint("WARNING: calling stub CacheCreateAndAddNode()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int CacheCreateAndAddNodeWithIPAddresses()
{
	DbgPrint("WARNING: calling stub CacheCreateAndAddNodeWithIPAddresses()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int CacheDeleteNode()
{
	DbgPrint("WARNING: calling stub CacheDeleteNode()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int CacheIsNameCluster()
{
	DbgPrint("WARNING: calling stub CacheIsNameCluster()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int CacheIsNameInNodeList()
{
	DbgPrint("WARNING: calling stub CacheIsNameInNodeList()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int CallDrvDevModeConversion()
{
	DbgPrint("WARNING: calling stub CallDrvDevModeConversion()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int CallRouterFindFirstPrinterChangeNotification()
{
	DbgPrint("WARNING: calling stub CallRouterFindFirstPrinterChangeNotification()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int CheckLocalCall()
{
	DbgPrint("WARNING: calling stub CheckLocalCall()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int ClusterSplClose()
{
	DbgPrint("WARNING: calling stub ClusterSplClose()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int ClusterSplIsAlive()
{
	DbgPrint("WARNING: calling stub ClusterSplIsAlive()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int ClusterSplOpen()
{
	DbgPrint("WARNING: calling stub ClusterSplOpen()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int ConfigurePortW()
{
	DbgPrint("WARNING: calling stub ConfigurePortW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int CreatePrinterIC()
{
	DbgPrint("WARNING: calling stub CreatePrinterIC()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DbgGetPointers()
{
	DbgPrint("WARNING: calling stub DbgGetPointers()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeleteFormW()
{
	DbgPrint("WARNING: calling stub DeleteFormW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeleteMonitorW()
{
	DbgPrint("WARNING: calling stub DeleteMonitorW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeletePerMachineConnectionW()
{
	DbgPrint("WARNING: calling stub DeletePerMachineConnectionW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeletePortW()
{
	DbgPrint("WARNING: calling stub DeletePortW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeletePrinter()
{
	DbgPrint("WARNING: calling stub DeletePrinter()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeletePrinterConnectionW()
{
	DbgPrint("WARNING: calling stub DeletePrinterConnectionW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeletePrinterDataExW()
{
	DbgPrint("WARNING: calling stub DeletePrinterDataExW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeletePrinterDataW()
{
	DbgPrint("WARNING: calling stub DeletePrinterDataW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeletePrinterDriverExW()
{
	DbgPrint("WARNING: calling stub DeletePrinterDriverExW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeletePrinterDriverW()
{
	DbgPrint("WARNING: calling stub DeletePrinterDriverW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeletePrinterIC()
{
	DbgPrint("WARNING: calling stub DeletePrinterIC()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeletePrinterKeyW()
{
	DbgPrint("WARNING: calling stub DeletePrinterKeyW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeletePrintProcessorW()
{
	DbgPrint("WARNING: calling stub DeletePrintProcessorW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int DeletePrintProvidorW()
{
	DbgPrint("WARNING: calling stub DeletePrintProvidorW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int EnumFormsW()
{
	DbgPrint("WARNING: calling stub EnumFormsW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int EnumPerMachineConnectionsW()
{
	DbgPrint("WARNING: calling stub EnumPerMachineConnectionsW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int EnumPrinterDataExW()
{
	DbgPrint("WARNING: calling stub EnumPrinterDataExW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int EnumPrinterDataW()
{
	DbgPrint("WARNING: calling stub EnumPrinterDataW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int EnumPrinterDriversW()
{
	DbgPrint("WARNING: calling stub EnumPrinterDriversW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int EnumPrinterKeyW()
{
	DbgPrint("WARNING: calling stub EnumPrinterKeyW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int FindClosePrinterChangeNotification()
{
	DbgPrint("WARNING: calling stub FindClosePrinterChangeNotification()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int FlushPrinter()
{
	DbgPrint("WARNING: calling stub FlushPrinter()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int FormatPrinterForRegistryKey()
{
	DbgPrint("WARNING: calling stub FormatPrinterForRegistryKey()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int FormatRegistryKeyForPrinter()
{
	DbgPrint("WARNING: calling stub FormatRegistryKeyForPrinter()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int FreeOtherNames()
{
	DbgPrint("WARNING: calling stub FreeOtherNames()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int GetClientUserHandle()
{
	DbgPrint("WARNING: calling stub GetClientUserHandle()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int GetFormW()
{
	DbgPrint("WARNING: calling stub GetFormW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int GetJobAttributes()
{
	DbgPrint("WARNING: calling stub GetJobAttributes()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int GetNetworkId()
{
	DbgPrint("WARNING: calling stub GetNetworkId()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int GetPrinterDriverDirectoryW()
{
	DbgPrint("WARNING: calling stub GetPrinterDriverDirectoryW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int GetPrinterDriverExW()
{
	DbgPrint("WARNING: calling stub GetPrinterDriverExW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int GetServerPolicy()
{
	DbgPrint("WARNING: calling stub GetServerPolicy()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int GetShrinkedSize()
{
	DbgPrint("WARNING: calling stub GetShrinkedSize()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int IsNamedPipeRpcCall()
{
	DbgPrint("WARNING: calling stub IsNamedPipeRpcCall()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int LoadDriver()
{
	DbgPrint("WARNING: calling stub LoadDriver()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int LoadDriverFiletoConvertDevmode()
{
	DbgPrint("WARNING: calling stub LoadDriverFiletoConvertDevmode()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int LoadDriverWithVersion()
{
	DbgPrint("WARNING: calling stub LoadDriverWithVersion()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int LogWmiTraceEvent()
{
	DbgPrint("WARNING: calling stub LogWmiTraceEvent()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int MarshallDownStructuresArray()
{
	DbgPrint("WARNING: calling stub MarshallDownStructuresArray()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int MarshallUpStructure()
{
	DbgPrint("WARNING: calling stub MarshallUpStructure()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int MarshallUpStructuresArray()
{
	DbgPrint("WARNING: calling stub MarshallUpStructuresArray()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int MIDL_user_allocate1()
{
	DbgPrint("WARNING: calling stub MIDL_user_allocate1()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int MIDL_user_free1()
{
	DbgPrint("WARNING: calling stub MIDL_user_free1()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int OldGetPrinterDriverW()
{
	DbgPrint("WARNING: calling stub OldGetPrinterDriverW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int OpenPrinterExW()
{
	DbgPrint("WARNING: calling stub OpenPrinterExW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int OpenPrinterPortW()
{
	DbgPrint("WARNING: calling stub OpenPrinterPortW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int PartialReplyPrinterChangeNotification()
{
	DbgPrint("WARNING: calling stub PartialReplyPrinterChangeNotification()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int PlayGdiScriptOnPrinterIC()
{
	DbgPrint("WARNING: calling stub PlayGdiScriptOnPrinterIC()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int PrinterHandleRundown()
{
	DbgPrint("WARNING: calling stub PrinterHandleRundown()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int PrinterMessageBoxW()
{
	DbgPrint("WARNING: calling stub PrinterMessageBoxW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int ProvidorFindClosePrinterChangeNotification()
{
	DbgPrint("WARNING: calling stub ProvidorFindClosePrinterChangeNotification()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int ProvidorFindFirstPrinterChangeNotification()
{
	DbgPrint("WARNING: calling stub ProvidorFindFirstPrinterChangeNotification()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int pszDbgAllocMsgA()
{
	DbgPrint("WARNING: calling stub pszDbgAllocMsgA()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int RemoteFindFirstPrinterChangeNotification()
{
	DbgPrint("WARNING: calling stub RemoteFindFirstPrinterChangeNotification()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int ReplyClosePrinter()
{
	DbgPrint("WARNING: calling stub ReplyClosePrinter()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int ReplyOpenPrinter()
{
	DbgPrint("WARNING: calling stub ReplyOpenPrinter()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int ReplyPrinterChangeNotification()
{
	DbgPrint("WARNING: calling stub ReplyPrinterChangeNotification()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int ResetPrinterW()
{
	DbgPrint("WARNING: calling stub ResetPrinterW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int RouterAllocBidiMem()
{
	DbgPrint("WARNING: calling stub RouterAllocBidiMem()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int RouterAllocBidiResponseContainer()
{
	DbgPrint("WARNING: calling stub RouterAllocBidiResponseContainer()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int RouterAllocPrinterNotifyInfo()
{
	DbgPrint("WARNING: calling stub RouterAllocPrinterNotifyInfo()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int RouterFindFirstPrinterChangeNotification()
{
	DbgPrint("WARNING: calling stub RouterFindFirstPrinterChangeNotification()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int RouterFindNextPrinterChangeNotification()
{
	DbgPrint("WARNING: calling stub RouterFindNextPrinterChangeNotification()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int RouterFreeBidiMem()
{
	DbgPrint("WARNING: calling stub RouterFreeBidiMem()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int RouterFreePrinterNotifyInfo()
{
	DbgPrint("WARNING: calling stub RouterFreePrinterNotifyInfo()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int RouterRefreshPrinterChangeNotification()
{
	DbgPrint("WARNING: calling stub RouterRefreshPrinterChangeNotification()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int RouterReplyPrinter()
{
	DbgPrint("WARNING: calling stub RouterReplyPrinter()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SeekPrinter()
{
	DbgPrint("WARNING: calling stub SeekPrinter()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SendRecvBidiData()
{
	DbgPrint("WARNING: calling stub SendRecvBidiData()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SetAllocFailCount()
{
	DbgPrint("WARNING: calling stub SetAllocFailCount()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SetFormW()
{
	DbgPrint("WARNING: calling stub SetFormW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SetPortW()
{
	DbgPrint("WARNING: calling stub SetPortW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SetPrinterW()
{
	DbgPrint("WARNING: calling stub SetPrinterW()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SplCloseSpoolFileHandle()
{
	DbgPrint("WARNING: calling stub SplCloseSpoolFileHandle()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SplCommitSpoolData()
{
	DbgPrint("WARNING: calling stub SplCommitSpoolData()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SplDriverUnloadComplete()
{
	DbgPrint("WARNING: calling stub SplDriverUnloadComplete()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SplGetSpoolFileInfo()
{
	DbgPrint("WARNING: calling stub SplGetSpoolFileInfo()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SplIsSessionZero()
{
	DbgPrint("WARNING: calling stub SplIsSessionZero()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SplPowerEvent()
{
	DbgPrint("WARNING: calling stub SplPowerEvent()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SplProcessPnPEvent()
{
	DbgPrint("WARNING: calling stub SplProcessPnPEvent()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SplPromptUIInUsersSession()
{
	DbgPrint("WARNING: calling stub SplPromptUIInUsersSession()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SplReadPrinter()
{
	DbgPrint("WARNING: calling stub SplReadPrinter()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SplRegisterForDeviceEvents()
{
	DbgPrint("WARNING: calling stub SplRegisterForDeviceEvents()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SplShutDownRouter()
{
	DbgPrint("WARNING: calling stub SplShutDownRouter()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SplUnregisterForDeviceEvents()
{
	DbgPrint("WARNING: calling stub SplUnregisterForDeviceEvents()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SpoolerFindClosePrinterChangeNotification()
{
	DbgPrint("WARNING: calling stub SpoolerFindClosePrinterChangeNotification()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SpoolerFindFirstPrinterChangeNotification()
{
	DbgPrint("WARNING: calling stub SpoolerFindFirstPrinterChangeNotification()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SpoolerFindNextPrinterChangeNotification()
{
	DbgPrint("WARNING: calling stub SpoolerFindNextPrinterChangeNotification()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SpoolerFreePrinterNotifyInfo()
{
	DbgPrint("WARNING: calling stub SpoolerFreePrinterNotifyInfo()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int SpoolerHasInitialized()
{
	DbgPrint("WARNING: calling stub SpoolerHasInitialized()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int UndoAlignKMPtr()
{
	DbgPrint("WARNING: calling stub UndoAlignKMPtr()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int UnloadDriver()
{
	DbgPrint("WARNING: calling stub UnloadDriver()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int UnloadDriverFile()
{
	DbgPrint("WARNING: calling stub UnloadDriverFile()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int UpdateBufferSize()
{
	DbgPrint("WARNING: calling stub UpdateBufferSize()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int UpdatePrinterRegAll()
{
	DbgPrint("WARNING: calling stub UpdatePrinterRegAll()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int UpdatePrinterRegUser()
{
	DbgPrint("WARNING: calling stub UpdatePrinterRegUser()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int vDbgLogError()
{
	DbgPrint("WARNING: calling stub vDbgLogError()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int WaitForPrinterChange()
{
	DbgPrint("WARNING: calling stub WaitForPrinterChange()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

int WaitForSpoolerInitialization()
{
	DbgPrint("WARNING: calling stub WaitForSpoolerInitialization()\n");
	__wine_spec_unimplemented_stub("spoolss.dll", __FUNCTION__);
	return 0;
}

