/* This file is autogenerated, do not edit. */

#include <stubs.h>

int ImmActivateLayout()
{
	DbgPrint("WARNING: calling stub ImmActivateLayout()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmFreeLayout()
{
	DbgPrint("WARNING: calling stub ImmFreeLayout()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmGetImeInfoEx()
{
	DbgPrint("WARNING: calling stub ImmGetImeInfoEx()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmIMPGetIMEA()
{
	DbgPrint("WARNING: calling stub ImmIMPGetIMEA()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmIMPGetIMEW()
{
	DbgPrint("WARNING: calling stub ImmIMPGetIMEW()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmIMPQueryIMEA()
{
	DbgPrint("WARNING: calling stub ImmIMPQueryIMEA()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmIMPQueryIMEW()
{
	DbgPrint("WARNING: calling stub ImmIMPQueryIMEW()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmIMPSetIMEA()
{
	DbgPrint("WARNING: calling stub ImmIMPSetIMEA()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmIMPSetIMEW()
{
	DbgPrint("WARNING: calling stub ImmIMPSetIMEW()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmLoadIME()
{
	DbgPrint("WARNING: calling stub ImmLoadIME()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmLoadLayout()
{
	DbgPrint("WARNING: calling stub ImmLoadLayout()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmLockClientImc()
{
	DbgPrint("WARNING: calling stub ImmLockClientImc()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmLockImeDpi()
{
	DbgPrint("WARNING: calling stub ImmLockImeDpi()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmPenAuxInput()
{
	DbgPrint("WARNING: calling stub ImmPenAuxInput()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmPutImeMenuItemsIntoMappedFile()
{
	DbgPrint("WARNING: calling stub ImmPutImeMenuItemsIntoMappedFile()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmRegisterClient()
{
	DbgPrint("WARNING: calling stub ImmRegisterClient()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmSendIMEMessageExA()
{
	DbgPrint("WARNING: calling stub ImmSendIMEMessageExA()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmSendIMEMessageExW()
{
	DbgPrint("WARNING: calling stub ImmSendIMEMessageExW()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmSendMessageToActiveDefImeWndW()
{
	DbgPrint("WARNING: calling stub ImmSendMessageToActiveDefImeWndW()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmSetActiveContext()
{
	DbgPrint("WARNING: calling stub ImmSetActiveContext()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmSetActiveContextConsoleIME()
{
	DbgPrint("WARNING: calling stub ImmSetActiveContextConsoleIME()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmSystemHandler()
{
	DbgPrint("WARNING: calling stub ImmSystemHandler()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmUnlockClientImc()
{
	DbgPrint("WARNING: calling stub ImmUnlockClientImc()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmUnlockImeDpi()
{
	DbgPrint("WARNING: calling stub ImmUnlockImeDpi()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmWINNLSEnableIME()
{
	DbgPrint("WARNING: calling stub ImmWINNLSEnableIME()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmWINNLSGetEnableStatus()
{
	DbgPrint("WARNING: calling stub ImmWINNLSGetEnableStatus()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

int ImmWINNLSGetIMEHotkey()
{
	DbgPrint("WARNING: calling stub ImmWINNLSGetIMEHotkey()\n");
	__wine_spec_unimplemented_stub("imm32.dll", __FUNCTION__);
	return 0;
}

