/*** Autogenerated by WIDL <undefined version> from /home/jens/winos/reactos/sdk/include/reactos/idl/eventlogrpc.idl - Do not edit ***/
#include <string.h>

#include "/home/jens/winos/reactos/output-MinGW-i386/reactos/base/services/eventlog/eventlogrpc_s.h"

#ifndef DECLSPEC_HIDDEN
#define DECLSPEC_HIDDEN
#endif

#define TYPE_FORMAT_STRING_SIZE 685
#define PROC_FORMAT_STRING_SIZE 1597

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

static const NDR_RUNDOWN RundownRoutines[] =
{
    IELF_HANDLE_rundown
};

/*****************************************************************************
 * eventlog interface
 */

static const unsigned char * const eventlog__RpcProtseqEndpoint[][2] =
{
    { (const unsigned char *)"ncacn_np", (const unsigned char *)"\\pipe\\EventLog" },
};

static RPC_DISPATCH_TABLE eventlog_v0_0_DispatchTable;
static const MIDL_SERVER_INFO eventlog_ServerInfo;

static const RPC_SERVER_INTERFACE eventlog___RpcServerInterface =
{
    sizeof(RPC_SERVER_INTERFACE),
    {{0x82273fdc,0xe32a,0x18c3,{0x3f,0x78,0x82,0x79,0x29,0xdc,0x23,0xea}},{0,0}},
    {{0x8a885d04,0x1ceb,0x11c9,{0x9f,0xe8,0x08,0x00,0x2b,0x10,0x48,0x60}},{2,0}},
    &eventlog_v0_0_DispatchTable,
    1,
    (PRPC_PROTSEQ_ENDPOINT)eventlog__RpcProtseqEndpoint,
    0,
    &eventlog_ServerInfo,
    0,
};
RPC_IF_HANDLE eventlog_v0_0_s_ifspec DECLSPEC_HIDDEN = (RPC_IF_HANDLE)& eventlog___RpcServerInterface;

static const MIDL_STUB_DESC eventlog_StubDesc;

#if !defined(__RPC_WIN32__)
#error  Invalid build platform for this stub.
#endif

static const unsigned short eventlog_FormatStringOffsetTable[] =
{
    0,  /* ElfrClearELFW */
    48,  /* ElfrBackupELFW */
    96,  /* ElfrCloseEL */
    138,  /* ElfrDeregisterEventSource */
    180,  /* ElfrNumberOfRecords */
    228,  /* ElfrOldestRecord */
    276,  /* ElfrChangeNotify */
    330,  /* ElfrOpenELW */
    402,  /* ElfrRegisterEventSourceW */
    474,  /* ElfrOpenBELW */
    540,  /* ElfrReadELW */
    618,  /* ElfrReportEventW */
    738,  /* ElfrClearELFA */
    786,  /* ElfrBackupELFA */
    834,  /* ElfrOpenELA */
    906,  /* ElfrRegisterEventSourceA */
    978,  /* ElfrOpenBELA */
    1044,  /* ElfrReadELA */
    1122,  /* ElfrReportEventA */
    1242,  /* ElfrRegisterClusterSvc */
    1282,  /* ElfrDeregisterClusterSvc */
    1322,  /* ElfrWriteClusterEvents */
    1362,  /* ElfrGetLogInformation */
    1428,  /* ElfrFlushEL */
    1470,  /* ElfrReportEventAndSourceW */
};

static const MIDL_STUB_DESC eventlog_StubDesc =
{
    (void *)& eventlog___RpcServerInterface,
    MIDL_user_allocate,
    MIDL_user_free,
    {
        0,
    },
    RundownRoutines,
    0,
    0,
    0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50100a4, /* MIDL Version 5.1.164 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

static RPC_DISPATCH_FUNCTION eventlog_table[] =
{
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    0
};
static RPC_DISPATCH_TABLE eventlog_v0_0_DispatchTable =
{
    25,
    eventlog_table
};

static const SERVER_ROUTINE eventlog_ServerRoutineTable[] =
{
    (SERVER_ROUTINE)ElfrClearELFW,
    (SERVER_ROUTINE)ElfrBackupELFW,
    (SERVER_ROUTINE)ElfrCloseEL,
    (SERVER_ROUTINE)ElfrDeregisterEventSource,
    (SERVER_ROUTINE)ElfrNumberOfRecords,
    (SERVER_ROUTINE)ElfrOldestRecord,
    (SERVER_ROUTINE)ElfrChangeNotify,
    (SERVER_ROUTINE)ElfrOpenELW,
    (SERVER_ROUTINE)ElfrRegisterEventSourceW,
    (SERVER_ROUTINE)ElfrOpenBELW,
    (SERVER_ROUTINE)ElfrReadELW,
    (SERVER_ROUTINE)ElfrReportEventW,
    (SERVER_ROUTINE)ElfrClearELFA,
    (SERVER_ROUTINE)ElfrBackupELFA,
    (SERVER_ROUTINE)ElfrOpenELA,
    (SERVER_ROUTINE)ElfrRegisterEventSourceA,
    (SERVER_ROUTINE)ElfrOpenBELA,
    (SERVER_ROUTINE)ElfrReadELA,
    (SERVER_ROUTINE)ElfrReportEventA,
    (SERVER_ROUTINE)ElfrRegisterClusterSvc,
    (SERVER_ROUTINE)ElfrDeregisterClusterSvc,
    (SERVER_ROUTINE)ElfrWriteClusterEvents,
    (SERVER_ROUTINE)ElfrGetLogInformation,
    (SERVER_ROUTINE)ElfrFlushEL,
    (SERVER_ROUTINE)ElfrReportEventAndSourceW,
};

static const MIDL_SERVER_INFO eventlog_ServerInfo =
{
    &eventlog_StubDesc,
    eventlog_ServerRoutineTable,
    __MIDL_ProcFormatString.Format,
    eventlog_FormatStringOffsetTable,
    0,
    0,
    0,
    0
};

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure eventlog::ElfrClearELFW) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x0),	/* method 0 */
        NdrFcShort(0xc),	/* stack size = 12 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 30 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x2),	/* type offset = 2 */
/* 36 (parameter BackupFileName) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x2a),	/* type offset = 42 */
/* 42 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 48 (procedure eventlog::ElfrBackupELFW) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1),	/* method 1 */
        NdrFcShort(0xc),	/* stack size = 12 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 78 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x2e),	/* type offset = 46 */
/* 84 (parameter BackupFileName) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x32),	/* type offset = 50 */
/* 90 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 96 (procedure eventlog::ElfrCloseEL) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x2),	/* method 2 */
        NdrFcShort(0x8),	/* stack size = 8 */
        0x30,	/* FC_BIND_CONTEXT */
        0xe0,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x20),	/* server buffer = 32 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 126 (parameter LogHandle) */
        NdrFcShort(0x118),	/* flags: in, out, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x3a),	/* type offset = 58 */
/* 132 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 138 (procedure eventlog::ElfrDeregisterEventSource) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x8),	/* stack size = 8 */
        0x30,	/* FC_BIND_CONTEXT */
        0xe0,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x20),	/* server buffer = 32 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 168 (parameter LogHandle) */
        NdrFcShort(0x118),	/* flags: in, out, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x42),	/* type offset = 66 */
/* 174 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 180 (procedure eventlog::ElfrNumberOfRecords) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0xc),	/* stack size = 12 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x03,	/* 3 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 210 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x46),	/* type offset = 70 */
/* 216 (parameter NumberOfRecords) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x09,	/* FC_ULONG */
        0x0,
/* 222 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 228 (procedure eventlog::ElfrOldestRecord) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0xc),	/* stack size = 12 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x03,	/* 3 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 258 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x4e),	/* type offset = 78 */
/* 264 (parameter OldestRecordNumber) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x09,	/* FC_ULONG */
        0x0,
/* 270 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 276 (procedure eventlog::ElfrChangeNotify) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x14),	/* stack size = 20 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x2c),	/* client buffer = 44 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x04,	/* 4 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 306 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x56),	/* type offset = 86 */
/* 312 (parameter ClientId) */
        NdrFcShort(0x8a),	/* flags: must free, in, by value */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x5a),	/* type offset = 90 */
/* 318 (parameter Event) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x08,	/* FC_LONG */
        0x0,
/* 324 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 330 (procedure eventlog::ElfrOpenELW) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x1c),	/* stack size = 28 */
        0x31,	/* FC_BIND_GENERIC */
        0x04,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x5c,	/* FC_PAD */
        NdrFcShort(0x1e),	/* client buffer = 30 */
        NdrFcShort(0x20),	/* server buffer = 32 */
        0x46,
        0x07,	/* 7 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 360 (parameter UNCServerName) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x62),	/* type offset = 98 */
/* 366 (parameter ModuleName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x14),	/* type offset = 20 */
/* 372 (parameter RegModuleName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x14),	/* type offset = 20 */
/* 378 (parameter MajorVersion) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x08,	/* FC_LONG */
        0x0,
/* 384 (parameter MinorVersion) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 390 (parameter LogHandle) */
        NdrFcShort(0x110),	/* flags: out, simple ref */
        NdrFcShort(0x14),	/* stack offset = 20 */
        NdrFcShort(0x72),	/* type offset = 114 */
/* 396 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 402 (procedure eventlog::ElfrRegisterEventSourceW) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x1c),	/* stack size = 28 */
        0x31,	/* FC_BIND_GENERIC */
        0x04,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x5c,	/* FC_PAD */
        NdrFcShort(0x1e),	/* client buffer = 30 */
        NdrFcShort(0x20),	/* server buffer = 32 */
        0x46,
        0x07,	/* 7 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 432 (parameter UNCServerName) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x76),	/* type offset = 118 */
/* 438 (parameter ModuleName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x14),	/* type offset = 20 */
/* 444 (parameter RegModuleName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x14),	/* type offset = 20 */
/* 450 (parameter MajorVersion) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x08,	/* FC_LONG */
        0x0,
/* 456 (parameter MinorVersion) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 462 (parameter LogHandle) */
        NdrFcShort(0x110),	/* flags: out, simple ref */
        NdrFcShort(0x14),	/* stack offset = 20 */
        NdrFcShort(0x86),	/* type offset = 134 */
/* 468 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 474 (procedure eventlog::ElfrOpenBELW) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x9),	/* method 9 */
        NdrFcShort(0x18),	/* stack size = 24 */
        0x31,	/* FC_BIND_GENERIC */
        0x04,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x5c,	/* FC_PAD */
        NdrFcShort(0x1e),	/* client buffer = 30 */
        NdrFcShort(0x20),	/* server buffer = 32 */
        0x46,
        0x06,	/* 6 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 504 (parameter UNCServerName) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x8a),	/* type offset = 138 */
/* 510 (parameter BackupFileName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x14),	/* type offset = 20 */
/* 516 (parameter MajorVersion) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 522 (parameter MinorVersion) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x08,	/* FC_LONG */
        0x0,
/* 528 (parameter LogHandle) */
        NdrFcShort(0x110),	/* flags: out, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x96),	/* type offset = 150 */
/* 534 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x14),	/* stack offset = 20 */
        0x08,	/* FC_LONG */
        0x0,
/* 540 (procedure eventlog::ElfrReadELW) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xa),	/* method 10 */
        NdrFcShort(0x20),	/* stack size = 32 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x30),	/* client buffer = 48 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x45,
        0x08,	/* 8 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 570 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x9a),	/* type offset = 154 */
/* 576 (parameter ReadFlags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 582 (parameter RecordOffset) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 588 (parameter NumberOfBytesToRead) */
        NdrFcShort(0x88),	/* flags: in, by value */
        NdrFcShort(0xc),	/* stack offset = 12 */
        NdrFcShort(0x9e),	/* type offset = 158 */
/* 594 (parameter Buffer) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xa8),	/* type offset = 168 */
/* 600 (parameter NumberOfBytesRead) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x14),	/* stack offset = 20 */
        0x09,	/* FC_ULONG */
        0x0,
/* 606 (parameter MinNumberOfBytesNeeded) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x09,	/* FC_ULONG */
        0x0,
/* 612 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x1c),	/* stack offset = 28 */
        0x08,	/* FC_LONG */
        0x0,
/* 618 (procedure eventlog::ElfrReportEventW) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xb),	/* method 11 */
        NdrFcShort(0x3c),	/* stack size = 60 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x68),	/* client buffer = 104 */
        NdrFcShort(0x28),	/* server buffer = 40 */
        0x46,
        0x0f,	/* 15 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 648 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0xbe),	/* type offset = 190 */
/* 654 (parameter Time) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 660 (parameter EventType) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 666 (parameter EventCategory) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x06,	/* FC_SHORT */
        0x0,
/* 672 (parameter EventID) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 678 (parameter NumStrings) */
        NdrFcShort(0x88),	/* flags: in, by value */
        NdrFcShort(0x14),	/* stack offset = 20 */
        NdrFcShort(0xc2),	/* type offset = 194 */
/* 684 (parameter DataSize) */
        NdrFcShort(0x88),	/* flags: in, by value */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0xcc),	/* type offset = 204 */
/* 690 (parameter ComputerName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x1c),	/* stack offset = 28 */
        NdrFcShort(0x14),	/* type offset = 20 */
/* 696 (parameter UserSID) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x102),	/* type offset = 258 */
/* 702 (parameter Strings) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x24),	/* stack offset = 36 */
        NdrFcShort(0x126),	/* type offset = 294 */
/* 708 (parameter Data) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x134),	/* type offset = 308 */
/* 714 (parameter Flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x2c),	/* stack offset = 44 */
        0x06,	/* FC_SHORT */
        0x0,
/* 720 (parameter RecordNumber) */
        NdrFcShort(0x1a),	/* flags: must free, in, out */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0x138),	/* type offset = 312 */
/* 726 (parameter TimeWritten) */
        NdrFcShort(0x1a),	/* flags: must free, in, out */
        NdrFcShort(0x34),	/* stack offset = 52 */
        NdrFcShort(0x13c),	/* type offset = 316 */
/* 732 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0x08,	/* FC_LONG */
        0x0,
/* 738 (procedure eventlog::ElfrClearELFA) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xc),	/* method 12 */
        NdrFcShort(0xc),	/* stack size = 12 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 768 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x140),	/* type offset = 320 */
/* 774 (parameter BackupFileName) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x168),	/* type offset = 360 */
/* 780 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 786 (procedure eventlog::ElfrBackupELFA) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xd),	/* method 13 */
        NdrFcShort(0xc),	/* stack size = 12 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 816 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x16c),	/* type offset = 364 */
/* 822 (parameter BackupFileName) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x170),	/* type offset = 368 */
/* 828 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 834 (procedure eventlog::ElfrOpenELA) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xe),	/* method 14 */
        NdrFcShort(0x1c),	/* stack size = 28 */
        0x31,	/* FC_BIND_GENERIC */
        0x04,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x01,
        0x5c,	/* FC_PAD */
        NdrFcShort(0x1d),	/* client buffer = 29 */
        NdrFcShort(0x20),	/* server buffer = 32 */
        0x46,
        0x07,	/* 7 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 864 (parameter UNCServerName) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x174),	/* type offset = 372 */
/* 870 (parameter ModuleName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x152),	/* type offset = 338 */
/* 876 (parameter RegModuleName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x152),	/* type offset = 338 */
/* 882 (parameter MajorVersion) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x08,	/* FC_LONG */
        0x0,
/* 888 (parameter MinorVersion) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 894 (parameter LogHandle) */
        NdrFcShort(0x110),	/* flags: out, simple ref */
        NdrFcShort(0x14),	/* stack offset = 20 */
        NdrFcShort(0x184),	/* type offset = 388 */
/* 900 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 906 (procedure eventlog::ElfrRegisterEventSourceA) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xf),	/* method 15 */
        NdrFcShort(0x1c),	/* stack size = 28 */
        0x31,	/* FC_BIND_GENERIC */
        0x04,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x01,
        0x5c,	/* FC_PAD */
        NdrFcShort(0x1d),	/* client buffer = 29 */
        NdrFcShort(0x20),	/* server buffer = 32 */
        0x46,
        0x07,	/* 7 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 936 (parameter UNCServerName) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x188),	/* type offset = 392 */
/* 942 (parameter ModuleName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x152),	/* type offset = 338 */
/* 948 (parameter RegModuleName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x152),	/* type offset = 338 */
/* 954 (parameter MajorVersion) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x08,	/* FC_LONG */
        0x0,
/* 960 (parameter MinorVersion) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 966 (parameter LogHandle) */
        NdrFcShort(0x110),	/* flags: out, simple ref */
        NdrFcShort(0x14),	/* stack offset = 20 */
        NdrFcShort(0x198),	/* type offset = 408 */
/* 972 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 978 (procedure eventlog::ElfrOpenBELA) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x10),	/* method 16 */
        NdrFcShort(0x18),	/* stack size = 24 */
        0x31,	/* FC_BIND_GENERIC */
        0x04,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x01,
        0x5c,	/* FC_PAD */
        NdrFcShort(0x1d),	/* client buffer = 29 */
        NdrFcShort(0x20),	/* server buffer = 32 */
        0x46,
        0x06,	/* 6 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1008 (parameter UNCServerName) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x19c),	/* type offset = 412 */
/* 1014 (parameter BackupFileName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x152),	/* type offset = 338 */
/* 1020 (parameter MajorVersion) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1026 (parameter MinorVersion) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x08,	/* FC_LONG */
        0x0,
/* 1032 (parameter LogHandle) */
        NdrFcShort(0x110),	/* flags: out, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x1a8),	/* type offset = 424 */
/* 1038 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x14),	/* stack offset = 20 */
        0x08,	/* FC_LONG */
        0x0,
/* 1044 (procedure eventlog::ElfrReadELA) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x11),	/* method 17 */
        NdrFcShort(0x20),	/* stack size = 32 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x30),	/* client buffer = 48 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x45,
        0x08,	/* 8 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1074 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x1ac),	/* type offset = 428 */
/* 1080 (parameter ReadFlags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 1086 (parameter RecordOffset) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1092 (parameter NumberOfBytesToRead) */
        NdrFcShort(0x88),	/* flags: in, by value */
        NdrFcShort(0xc),	/* stack offset = 12 */
        NdrFcShort(0x1b0),	/* type offset = 432 */
/* 1098 (parameter Buffer) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x1ba),	/* type offset = 442 */
/* 1104 (parameter NumberOfBytesRead) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x14),	/* stack offset = 20 */
        0x09,	/* FC_ULONG */
        0x0,
/* 1110 (parameter MinNumberOfBytesNeeded) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x09,	/* FC_ULONG */
        0x0,
/* 1116 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x1c),	/* stack offset = 28 */
        0x08,	/* FC_LONG */
        0x0,
/* 1122 (procedure eventlog::ElfrReportEventA) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x12),	/* method 18 */
        NdrFcShort(0x3c),	/* stack size = 60 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x68),	/* client buffer = 104 */
        NdrFcShort(0x28),	/* server buffer = 40 */
        0x46,
        0x0f,	/* 15 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1152 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x1d0),	/* type offset = 464 */
/* 1158 (parameter Time) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 1164 (parameter EventType) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1170 (parameter EventCategory) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1176 (parameter EventID) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1182 (parameter NumStrings) */
        NdrFcShort(0x88),	/* flags: in, by value */
        NdrFcShort(0x14),	/* stack offset = 20 */
        NdrFcShort(0x1d4),	/* type offset = 468 */
/* 1188 (parameter DataSize) */
        NdrFcShort(0x88),	/* flags: in, by value */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x1de),	/* type offset = 478 */
/* 1194 (parameter ComputerName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x1c),	/* stack offset = 28 */
        NdrFcShort(0x152),	/* type offset = 338 */
/* 1200 (parameter UserSID) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x1ec),	/* type offset = 492 */
/* 1206 (parameter Strings) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x24),	/* stack offset = 36 */
        NdrFcShort(0x210),	/* type offset = 528 */
/* 1212 (parameter Data) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x21e),	/* type offset = 542 */
/* 1218 (parameter Flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x2c),	/* stack offset = 44 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1224 (parameter RecordNumber) */
        NdrFcShort(0x1a),	/* flags: must free, in, out */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0x222),	/* type offset = 546 */
/* 1230 (parameter TimeWritten) */
        NdrFcShort(0x1a),	/* flags: must free, in, out */
        NdrFcShort(0x34),	/* stack offset = 52 */
        NdrFcShort(0x226),	/* type offset = 550 */
/* 1236 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0x08,	/* FC_LONG */
        0x0,
/* 1242 (procedure eventlog::ElfrRegisterClusterSvc) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x13),	/* method 19 */
        NdrFcShort(0x8),	/* stack size = 8 */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x00,
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1270 (parameter BindingHandle) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1276 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 1282 (procedure eventlog::ElfrDeregisterClusterSvc) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x14),	/* method 20 */
        NdrFcShort(0x8),	/* stack size = 8 */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x00,
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1310 (parameter BindingHandle) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1316 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 1322 (procedure eventlog::ElfrWriteClusterEvents) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x15),	/* method 21 */
        NdrFcShort(0x8),	/* stack size = 8 */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x00,
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1350 (parameter BindingHandle) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1356 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 1362 (procedure eventlog::ElfrGetLogInformation) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x16),	/* method 22 */
        NdrFcShort(0x18),	/* stack size = 24 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x28),	/* client buffer = 40 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x45,
        0x06,	/* 6 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1392 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x22a),	/* type offset = 554 */
/* 1398 (parameter InfoLevel) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 1404 (parameter Buffer) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x22e),	/* type offset = 558 */
/* 1410 (parameter cbBufSize) */
        NdrFcShort(0x88),	/* flags: in, by value */
        NdrFcShort(0xc),	/* stack offset = 12 */
        NdrFcShort(0x23c),	/* type offset = 572 */
/* 1416 (parameter pcbBytesNeeded) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 1422 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x14),	/* stack offset = 20 */
        0x08,	/* FC_LONG */
        0x0,
/* 1428 (procedure eventlog::ElfrFlushEL) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x17),	/* method 23 */
        NdrFcShort(0x8),	/* stack size = 8 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1458 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x24a),	/* type offset = 586 */
/* 1464 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 1470 (procedure eventlog::ElfrReportEventAndSourceW) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x18),	/* method 24 */
        NdrFcShort(0x40),	/* stack size = 64 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x68),	/* client buffer = 104 */
        NdrFcShort(0x28),	/* server buffer = 40 */
        0x46,
        0x10,	/* 16 params */
        0x08,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1500 (parameter LogHandle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x24e),	/* type offset = 590 */
/* 1506 (parameter Time) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 1512 (parameter EventType) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1518 (parameter EventCategory) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1524 (parameter EventID) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1530 (parameter SourceName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x14),	/* stack offset = 20 */
        NdrFcShort(0x14),	/* type offset = 20 */
/* 1536 (parameter NumStrings) */
        NdrFcShort(0x88),	/* flags: in, by value */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x256),	/* type offset = 598 */
/* 1542 (parameter DataSize) */
        NdrFcShort(0x88),	/* flags: in, by value */
        NdrFcShort(0x1c),	/* stack offset = 28 */
        NdrFcShort(0x260),	/* type offset = 608 */
/* 1548 (parameter ComputerName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x14),	/* type offset = 20 */
/* 1554 (parameter UserSID) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x24),	/* stack offset = 36 */
        NdrFcShort(0x26e),	/* type offset = 622 */
/* 1560 (parameter Strings) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x292),	/* type offset = 658 */
/* 1566 (parameter Data) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x2c),	/* stack offset = 44 */
        NdrFcShort(0x2a0),	/* type offset = 672 */
/* 1572 (parameter Flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1578 (parameter RecordNumber) */
        NdrFcShort(0x1a),	/* flags: must free, in, out */
        NdrFcShort(0x34),	/* stack offset = 52 */
        NdrFcShort(0x2a4),	/* type offset = 676 */
/* 1584 (parameter TimeWritten) */
        NdrFcShort(0x1a),	/* flags: must free, in, out */
        NdrFcShort(0x38),	/* stack offset = 56 */
        NdrFcShort(0x2a8),	/* type offset = 680 */
/* 1590 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x3c),	/* stack offset = 60 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 6 (LPWSTR) */
        0x1c,	/* FC_CVARRAY */
        0x1,	/* 1 */
        NdrFcShort(0x2),	/* 2 */
        0x17,	/* Corr desc: field pointer MaximumLength, FC_USHORT */
        0x55,	/* FC_DIV_2 */
        NdrFcShort(0x2),	/* offset = 2 */
        0x17,	/* Corr desc: field pointer Length, FC_USHORT */
        0x55,	/* FC_DIV_2 */
        NdrFcShort(0x0),	/* offset = 0 */
        0x05,	/* FC_WCHAR */
        0x5b,	/* FC_END */
/* 20 (struct _RPC_UNICODE_STRING) */
        0x16,	/* FC_PSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x4b,	/* FC_PP */
        0x5c,	/* FC_PAD */
        0x46, /* FC_NO_REPEAT */
        0x5c, /* FC_PAD */
        NdrFcShort(0x4),	/* Memory offset = 4 */
        NdrFcShort(0x4),	/* Buffer offset = 4 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe4),	/* Offset= -28 (6) */
        0x5b,	/* FC_END */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x8,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 42 (PRPC_UNICODE_STRING) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe8),	/* Offset= -24 (20) */
/* 46 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 50 (PRPC_UNICODE_STRING) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe0),	/* Offset= -32 (20) */
/* 54 (PIELF_HANDLE) */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0x2),	 /* Offset= 2 (58) */
/* 58 */
        0x30,	/* FC_BIND_CONTEXT */
        0xe0,	/* Context flags: out, in, via ptr, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 62 (PIELF_HANDLE) */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0x2),	 /* Offset= 2 (66) */
/* 66 */
        0x30,	/* FC_BIND_CONTEXT */
        0xe0,	/* Context flags: out, in, via ptr, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 70 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 74 (PULONG) */
        0x11, 0xc,	/* FC_RP [allocated_on_stack] [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 78 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 82 (PULONG) */
        0x11, 0xc,	/* FC_RP [allocated_on_stack] [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 86 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 90 (RPC_CLIENT_ID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 98 (EVENTLOG_HANDLE_W) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x05,	/* FC_WCHAR */
        0x5c,	/* FC_PAD */
/* 102 (PRPC_UNICODE_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffac),	/* Offset= -84 (20) */
/* 106 (PRPC_UNICODE_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffa8),	/* Offset= -88 (20) */
/* 110 (PIELF_HANDLE) */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0x2),	 /* Offset= 2 (114) */
/* 114 */
        0x30,	/* FC_BIND_CONTEXT */
        0xa0,	/* Context flags: out, via ptr, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 118 (EVENTLOG_HANDLE_W) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x05,	/* FC_WCHAR */
        0x5c,	/* FC_PAD */
/* 122 (PRPC_UNICODE_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff98),	/* Offset= -104 (20) */
/* 126 (PRPC_UNICODE_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff94),	/* Offset= -108 (20) */
/* 130 (PIELF_HANDLE) */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0x2),	 /* Offset= 2 (134) */
/* 134 */
        0x30,	/* FC_BIND_CONTEXT */
        0xa0,	/* Context flags: out, via ptr, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 138 (EVENTLOG_HANDLE_W) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x05,	/* FC_WCHAR */
        0x5c,	/* FC_PAD */
/* 142 (PRPC_UNICODE_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff84),	/* Offset= -124 (20) */
/* 146 (PIELF_HANDLE) */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0x2),	 /* Offset= 2 (150) */
/* 150 */
        0x30,	/* FC_BIND_CONTEXT */
        0xa0,	/* Context flags: out, via ptr, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 154 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 158 */
        0xb7,	/* FC_RANGE */
        0x9,	/* FC_ULONG */
        NdrFcLong(0x0),	/* 0 */
        NdrFcLong(0x7ffff),	/* 524287 */
/* 168 (PBYTE) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x29,	/* Corr desc: parameter NumberOfBytesToRead, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xc),	/* offset = 12 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 178 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff4),	/* Offset= -12 (168) */
/* 182 (PULONG) */
        0x11, 0xc,	/* FC_RP [allocated_on_stack] [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 186 (PULONG) */
        0x11, 0xc,	/* FC_RP [allocated_on_stack] [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 190 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 194 */
        0xb7,	/* FC_RANGE */
        0x7,	/* FC_USHORT */
        NdrFcLong(0x0),	/* 0 */
        NdrFcLong(0x100),	/* 256 */
/* 204 */
        0xb7,	/* FC_RANGE */
        0x9,	/* FC_ULONG */
        NdrFcLong(0x0),	/* 0 */
        NdrFcLong(0x3ffff),	/* 262143 */
/* 214 (PRPC_UNICODE_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff3c),	/* Offset= -196 (20) */
/* 218 (BYTE[6]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x6),	/* 6 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 224 (SID_IDENTIFIER_AUTHORITY) */
        0x15,	/* FC_STRUCT */
        0x0,	/* 0 */
        NdrFcShort(0x6),	/* 6 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff4),	/* Offset= -12 (218) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 234 (DWORD[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x3,	/* Corr desc: field SubAuthorityCount, FC_SMALL */
        0x0,	/* no operators */
        NdrFcShort(0xfff9),	/* offset = -7 */
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 244 (struct _RPC_SID) */
        0x17,	/* FC_CSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0xfff2),	/* Offset= -14 (234) */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe2),	/* Offset= -30 (224) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 258 (PRPC_SID) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff0),	/* Offset= -16 (244) */
/* 262 (PRPC_UNICODE_STRING[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x27,	/* Corr desc: parameter NumStrings, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0x14),	/* offset = 20 */
        0x4b,	/* FC_PP */
        0x5c,	/* FC_PAD */
        0x48, /* FC_VARIABLE_REPEAT */
        0x49, /* FC_FIXED_OFFSET */
        NdrFcShort(0x4),	/* Increment = 4 */
        NdrFcShort(0x0),	/* Offset to array = 0 */
        NdrFcShort(0x1),	/* Number of pointers = 1 */
        NdrFcShort(0x0),	/* Memory offset = 0 */
        NdrFcShort(0x0),	/* Buffer offset = 0 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfef6),	/* Offset= -266 (20) */
        0x5b,	/* FC_END */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfef1),	/* Offset= -271 (20) */
        0x5b,	/* FC_END */
/* 294 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffde),	/* Offset= -34 (262) */
/* 298 (PBYTE) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x29,	/* Corr desc: parameter DataSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x18),	/* offset = 24 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 308 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xfff4),	/* Offset= -12 (298) */
/* 312 (PULONG) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 316 (PULONG) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 320 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 324 (LPSTR) */
        0x1c,	/* FC_CVARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x17,	/* Corr desc: field pointer MaximumLength, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0x2),	/* offset = 2 */
        0x17,	/* Corr desc: field pointer Length, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 338 (struct _RPC_STRING) */
        0x16,	/* FC_PSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x4b,	/* FC_PP */
        0x5c,	/* FC_PAD */
        0x46, /* FC_NO_REPEAT */
        0x5c, /* FC_PAD */
        NdrFcShort(0x4),	/* Memory offset = 4 */
        NdrFcShort(0x4),	/* Buffer offset = 4 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe4),	/* Offset= -28 (324) */
        0x5b,	/* FC_END */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x8,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 360 (PRPC_STRING) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe8),	/* Offset= -24 (338) */
/* 364 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 368 (PRPC_STRING) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe0),	/* Offset= -32 (338) */
/* 372 (EVENTLOG_HANDLE_A) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x02,	/* FC_CHAR */
        0x5c,	/* FC_PAD */
/* 376 (PRPC_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffd8),	/* Offset= -40 (338) */
/* 380 (PRPC_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffd4),	/* Offset= -44 (338) */
/* 384 (PIELF_HANDLE) */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0x2),	 /* Offset= 2 (388) */
/* 388 */
        0x30,	/* FC_BIND_CONTEXT */
        0xa0,	/* Context flags: out, via ptr, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 392 (EVENTLOG_HANDLE_A) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x02,	/* FC_CHAR */
        0x5c,	/* FC_PAD */
/* 396 (PRPC_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffc4),	/* Offset= -60 (338) */
/* 400 (PRPC_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffc0),	/* Offset= -64 (338) */
/* 404 (PIELF_HANDLE) */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0x2),	 /* Offset= 2 (408) */
/* 408 */
        0x30,	/* FC_BIND_CONTEXT */
        0xa0,	/* Context flags: out, via ptr, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 412 (EVENTLOG_HANDLE_A) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x02,	/* FC_CHAR */
        0x5c,	/* FC_PAD */
/* 416 (PRPC_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffb0),	/* Offset= -80 (338) */
/* 420 (PIELF_HANDLE) */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0x2),	 /* Offset= 2 (424) */
/* 424 */
        0x30,	/* FC_BIND_CONTEXT */
        0xa0,	/* Context flags: out, via ptr, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 428 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 432 */
        0xb7,	/* FC_RANGE */
        0x9,	/* FC_ULONG */
        NdrFcLong(0x0),	/* 0 */
        NdrFcLong(0x7ffff),	/* 524287 */
/* 442 (PBYTE) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x29,	/* Corr desc: parameter NumberOfBytesToRead, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xc),	/* offset = 12 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 452 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff4),	/* Offset= -12 (442) */
/* 456 (PULONG) */
        0x11, 0xc,	/* FC_RP [allocated_on_stack] [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 460 (PULONG) */
        0x11, 0xc,	/* FC_RP [allocated_on_stack] [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 464 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 468 */
        0xb7,	/* FC_RANGE */
        0x7,	/* FC_USHORT */
        NdrFcLong(0x0),	/* 0 */
        NdrFcLong(0x100),	/* 256 */
/* 478 */
        0xb7,	/* FC_RANGE */
        0x9,	/* FC_ULONG */
        NdrFcLong(0x0),	/* 0 */
        NdrFcLong(0x3ffff),	/* 262143 */
/* 488 (PRPC_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff68),	/* Offset= -152 (338) */
/* 492 (PRPC_SID) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xff06),	/* Offset= -250 (244) */
/* 496 (PRPC_STRING[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x27,	/* Corr desc: parameter NumStrings, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0x14),	/* offset = 20 */
        0x4b,	/* FC_PP */
        0x5c,	/* FC_PAD */
        0x48, /* FC_VARIABLE_REPEAT */
        0x49, /* FC_FIXED_OFFSET */
        NdrFcShort(0x4),	/* Increment = 4 */
        NdrFcShort(0x0),	/* Offset to array = 0 */
        NdrFcShort(0x1),	/* Number of pointers = 1 */
        NdrFcShort(0x0),	/* Memory offset = 0 */
        NdrFcShort(0x0),	/* Buffer offset = 0 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xff4a),	/* Offset= -182 (338) */
        0x5b,	/* FC_END */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xff45),	/* Offset= -187 (338) */
        0x5b,	/* FC_END */
/* 528 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffde),	/* Offset= -34 (496) */
/* 532 (PBYTE) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x29,	/* Corr desc: parameter DataSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x18),	/* offset = 24 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 542 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xfff4),	/* Offset= -12 (532) */
/* 546 (PULONG) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 550 (PULONG) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 554 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 558 (PBYTE) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x29,	/* Corr desc: parameter cbBufSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xc),	/* offset = 12 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 568 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff4),	/* Offset= -12 (558) */
/* 572 */
        0xb7,	/* FC_RANGE */
        0x9,	/* FC_ULONG */
        NdrFcLong(0x0),	/* 0 */
        NdrFcLong(0x400),	/* 1024 */
/* 582 (PULONG) */
        0x11, 0xc,	/* FC_RP [allocated_on_stack] [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 586 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 590 (IELF_HANDLE) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 594 (PRPC_UNICODE_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfdc0),	/* Offset= -576 (20) */
/* 598 */
        0xb7,	/* FC_RANGE */
        0x7,	/* FC_USHORT */
        NdrFcLong(0x0),	/* 0 */
        NdrFcLong(0x100),	/* 256 */
/* 608 */
        0xb7,	/* FC_RANGE */
        0x9,	/* FC_ULONG */
        NdrFcLong(0x0),	/* 0 */
        NdrFcLong(0x3ffff),	/* 262143 */
/* 618 (PRPC_UNICODE_STRING) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfda8),	/* Offset= -600 (20) */
/* 622 (PRPC_SID) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfe84),	/* Offset= -380 (244) */
/* 626 (PRPC_UNICODE_STRING[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x27,	/* Corr desc: parameter NumStrings, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0x18),	/* offset = 24 */
        0x4b,	/* FC_PP */
        0x5c,	/* FC_PAD */
        0x48, /* FC_VARIABLE_REPEAT */
        0x49, /* FC_FIXED_OFFSET */
        NdrFcShort(0x4),	/* Increment = 4 */
        NdrFcShort(0x0),	/* Offset to array = 0 */
        NdrFcShort(0x1),	/* Number of pointers = 1 */
        NdrFcShort(0x0),	/* Memory offset = 0 */
        NdrFcShort(0x0),	/* Buffer offset = 0 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfd8a),	/* Offset= -630 (20) */
        0x5b,	/* FC_END */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfd85),	/* Offset= -635 (20) */
        0x5b,	/* FC_END */
/* 658 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffde),	/* Offset= -34 (626) */
/* 662 (PBYTE) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x29,	/* Corr desc: parameter DataSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x1c),	/* offset = 28 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 672 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xfff4),	/* Offset= -12 (662) */
/* 676 (PULONG) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 680 (PULONG) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
        0x0
    }
};

