/* This file is autogenerated, do not edit. */

#include <stubs.h>

int ConnectToPrinterDlg()
{
	DbgPrint("WARNING: calling stub ConnectToPrinterDlg()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int ConnectToPrinterPropertyPage()
{
	DbgPrint("WARNING: calling stub ConnectToPrinterPropertyPage()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int ConstructPrinterFriendlyName()
{
	DbgPrint("WARNING: calling stub ConstructPrinterFriendlyName()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int DllCanUnloadNow()
{
	DbgPrint("WARNING: calling stub DllCanUnloadNow()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int DllGetClassObject()
{
	DbgPrint("WARNING: calling stub DllGetClassObject()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int DocumentPropertiesWrap()
{
	DbgPrint("WARNING: calling stub DocumentPropertiesWrap()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int PnPInterface()
{
	DbgPrint("WARNING: calling stub PnPInterface()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int PrintNotifyTray_Exit()
{
	DbgPrint("WARNING: calling stub PrintNotifyTray_Exit()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int PrintNotifyTray_Init()
{
	DbgPrint("WARNING: calling stub PrintNotifyTray_Init()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int PrinterPropPageProvider()
{
	DbgPrint("WARNING: calling stub PrinterPropPageProvider()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int RegisterPrintNotify()
{
	DbgPrint("WARNING: calling stub RegisterPrintNotify()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int ShowErrorMessageHR()
{
	DbgPrint("WARNING: calling stub ShowErrorMessageHR()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int ShowErrorMessageSC()
{
	DbgPrint("WARNING: calling stub ShowErrorMessageSC()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int UnregisterPrintNotify()
{
	DbgPrint("WARNING: calling stub UnregisterPrintNotify()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int bFolderEnumPrinters()
{
	DbgPrint("WARNING: calling stub bFolderEnumPrinters()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int bFolderGetPrinter()
{
	DbgPrint("WARNING: calling stub bFolderGetPrinter()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int bFolderRefresh()
{
	DbgPrint("WARNING: calling stub bFolderRefresh()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int __stdcall bPrinterSetup(void* a0, long a1, long a2, void* a3, void* a4, void* a5)
{
	DbgPrint("WARNING: calling stub bPrinterSetup(0x%p,0x%lx,0x%lx,0x%p,0x%p,0x%p)\n", (void*)a0, (long)a1, (long)a2, (void*)a3, (void*)a4, (void*)a5);
	return 0;
}

int vDocumentDefaults()
{
	DbgPrint("WARNING: calling stub vDocumentDefaults()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int vPrinterPropPages()
{
	DbgPrint("WARNING: calling stub vPrinterPropPages()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int vQueueCreate()
{
	DbgPrint("WARNING: calling stub vQueueCreate()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

int vServerPropPages()
{
	DbgPrint("WARNING: calling stub vServerPropPages()\n");
	__wine_spec_unimplemented_stub("printui.dll", __FUNCTION__);
	return 0;
}

