/* Do not edit this file manually.
   This file is autogenerated by windmc.  */

//
//  The values are 32 bit layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      C    - is the Customer code flag
//
//      R    - is a reserved bit
//
//      Code - is the facility's status code
//
//      Sev  - is the severity code
//
//           Success - 00
//           Informational - 01
//           Warning - 02
//           Error - 03
//
//      Facility - is the facility code
//
//           System - 00ff
//           Application - 0fff
//

//
// MessageId: SAC_INIT_STATUS
//
#define SAC_INIT_STATUS  0x1

//
// MessageId: SAC_NEWLINE
//
#define SAC_NEWLINE  0x2

//
// MessageId: SAC_PROMPT
//
#define SAC_PROMPT  0x3

//
// MessageId: SACDRV_4
//
#define SACDRV_4  0x4

//
// MessageId: SACDRV_5
//
#define SACDRV_5  0x5

//
// MessageId: SACDRV_6
//
#define SACDRV_6  0x6

//
// MessageId: SACDRV_7
//
#define SACDRV_7  0x7

//
// MessageId: SACDRV_8
//
#define SACDRV_8  0x8

//
// MessageId: SACDRV_9
//
#define SACDRV_9  0x9

//
// MessageId: SACDRV_10
//
#define SACDRV_10  0xa

//
// MessageId: SAC_OUT_OF_MEMORY_PROMPT
//
#define SAC_OUT_OF_MEMORY_PROMPT  0xb

//
// MessageId: SACDRV_12
//
#define SACDRV_12  0xc

//
// MessageId: SACDRV_13
//
#define SACDRV_13  0xd

//
// MessageId: SACDRV_14
//
#define SACDRV_14  0xe

//
// MessageId: SACDRV_15
//
#define SACDRV_15  0xf

//
// MessageId: SACDRV_16
//
#define SACDRV_16  0x10

//
// MessageId: SACDRV_18
//
#define SACDRV_18  0x12

//
// MessageId: SACDRV_19
//
#define SACDRV_19  0x13

//
// MessageId: SACDRV_20
//
#define SACDRV_20  0x14

//
// MessageId: SACDRV_21
//
#define SACDRV_21  0x15

//
// MessageId: SACDRV_22
//
#define SACDRV_22  0x16

//
// MessageId: SACDRV_23
//
#define SACDRV_23  0x17

//
// MessageId: SACDRV_24
//
#define SACDRV_24  0x18

//
// MessageId: SACDRV_25
//
#define SACDRV_25  0x19

//
// MessageId: SACDRV_27
//
#define SACDRV_27  0x1b

//
// MessageId: SACDRV_28
//
#define SACDRV_28  0x1c

//
// MessageId: SACDRV_29
//
#define SACDRV_29  0x1d

//
// MessageId: SACDRV_31
//
#define SACDRV_31  0x1f

//
// MessageId: SACDRV_32
//
#define SACDRV_32  0x20

//
// MessageId: SAC_FAIL_PROMPT
//
#define SAC_FAIL_PROMPT  0x30

//
// MessageId: SACDRV_49
//
#define SACDRV_49  0x31

//
// MessageId: SACDRV_50
//
#define SACDRV_50  0x32

//
// MessageId: SACDRV_51
//
#define SACDRV_51  0x33

//
// MessageId: SACDRV_52
//
#define SACDRV_52  0x34

//
// MessageId: SACDRV_54
//
#define SACDRV_54  0x36

//
// MessageId: SACDRV_55
//
#define SACDRV_55  0x37

//
// MessageId: SACDRV_56
//
#define SACDRV_56  0x38

//
// MessageId: SACDRV_57
//
#define SACDRV_57  0x39

//
// MessageId: SACDRV_58
//
#define SACDRV_58  0x3a

//
// MessageId: SACDRV_59
//
#define SACDRV_59  0x3b

//
// MessageId: SACDRV_60
//
#define SACDRV_60  0x3c

//
// MessageId: SACDRV_61
//
#define SACDRV_61  0x3d

//
// MessageId: SACDRV_62
//
#define SACDRV_62  0x3e

//
// MessageId: SACDRV_63
//
#define SACDRV_63  0x3f

//
// MessageId: SACDRV_64
//
#define SACDRV_64  0x40

//
// MessageId: SAC_SHUTDOWN_FAIL_PROMPT
//
#define SAC_SHUTDOWN_FAIL_PROMPT  0x41

//
// MessageId: SAC_RESTART_FAIL_PROMPT
//
#define SAC_RESTART_FAIL_PROMPT  0x42

//
// MessageId: SACDRV_67
//
#define SACDRV_67  0x43

//
// MessageId: SACDRV_68
//
#define SACDRV_68  0x44

//
// MessageId: SACDRV_69
//
#define SACDRV_69  0x45

//
// MessageId: SACDRV_70
//
#define SACDRV_70  0x46

//
// MessageId: SACDRV_71
//
#define SACDRV_71  0x47

//
// MessageId: SACDRV_72
//
#define SACDRV_72  0x48

//
// MessageId: SACDRV_73
//
#define SACDRV_73  0x49

//
// MessageId: SACDRV_74
//
#define SACDRV_74  0x4a

//
// MessageId: SACDRV_75
//
#define SACDRV_75  0x4b

//
// MessageId: SACDRV_76
//
#define SACDRV_76  0x4c

//
// MessageId: SACDRV_77
//
#define SACDRV_77  0x4d

//
// MessageId: SACDRV_78
//
#define SACDRV_78  0x4e

//
// MessageId: SACDRV_79
//
#define SACDRV_79  0x4f

//
// MessageId: SACDRV_80
//
#define SACDRV_80  0x50

//
// MessageId: SACDRV_81
//
#define SACDRV_81  0x51

//
// MessageId: SACDRV_82
//
#define SACDRV_82  0x52

//
// MessageId: SACDRV_83
//
#define SACDRV_83  0x53

//
// MessageId: SACDRV_84
//
#define SACDRV_84  0x54

//
// MessageId: SACDRV_85
//
#define SACDRV_85  0x55

//
// MessageId: SACDRV_86
//
#define SACDRV_86  0x56

//
// MessageId: SACDRV_87
//
#define SACDRV_87  0x57

//
// MessageId: SACDRV_88
//
#define SACDRV_88  0x58

//
// MessageId: SACDRV_89
//
#define SACDRV_89  0x59

//
// MessageId: SACDRV_90
//
#define SACDRV_90  0x5a

//
// MessageId: SACDRV_92
//
#define SACDRV_92  0x5c

//
// MessageId: SACDRV_93
//
#define SACDRV_93  0x5d

//
// MessageId: SACDRV_94
//
#define SACDRV_94  0x5e

//
// MessageId: SACDRV_95
//
#define SACDRV_95  0x5f

//
// MessageId: SACDRV_96
//
#define SACDRV_96  0x60

//
// MessageId: SACDRV_97
//
#define SACDRV_97  0x61

//
// MessageId: SAC_NO_DATA_MSG
//
#define SAC_NO_DATA_MSG  0x62

//
// MessageId: SACDRV_99
//
#define SACDRV_99  0x63

//
// MessageId: SAC_DATACENTER_SUITE_MSG
//
#define SAC_DATACENTER_SUITE_MSG  0x64

//
// MessageId: SAC_EMBEDDED_SUITE_MSG
//
#define SAC_EMBEDDED_SUITE_MSG  0x65

//
// MessageId: SAC_ENTERPRISE_SUITE_MSG
//
#define SAC_ENTERPRISE_SUITE_MSG  0x66

//
// MessageId: SAC_NO_SUITE_MSG
//
#define SAC_NO_SUITE_MSG  0x67

//
// MessageId: SACDRV_104
//
#define SACDRV_104  0x68

//
// MessageId: SAC_UNKNOWN_COMMAND
//
#define SAC_UNKNOWN_COMMAND  0x69

//
// MessageId: SACDRV_106
//
#define SACDRV_106  0x6a

//
// MessageId: SACDRV_107
//
#define SACDRV_107  0x6b

//
// MessageId: SACDRV_108
//
#define SACDRV_108  0x6c

//
// MessageId: SACDRV_109
//
#define SACDRV_109  0x6d

//
// MessageId: SACDRV_110
//
#define SACDRV_110  0x6e

//
// MessageId: SACDRV_111
//
#define SACDRV_111  0x6f

//
// MessageId: SACDRV_112
//
#define SACDRV_112  0x70

//
// MessageId: SAC_RESTART_TIME_PROMPT
//
#define SAC_RESTART_TIME_PROMPT  0x71

//
// MessageId: SAC_RESTART_PROMPT
//
#define SAC_RESTART_PROMPT  0x72

//
// MessageId: SAC_SHUTDOWN_PROMPT
//
#define SAC_SHUTDOWN_PROMPT  0x73

//
// MessageId: SACDRV_116
//
#define SACDRV_116  0x74

//
// MessageId: SACDRV_119
//
#define SACDRV_119  0x77

//
// MessageId: SACDRV_120
//
#define SACDRV_120  0x78

//
// MessageId: SACDRV_121
//
#define SACDRV_121  0x79

//
// MessageId: SACDRV_128
//
#define SACDRV_128  0x80

//
// MessageId: SACDRV_131
//
#define SACDRV_131  0x83

//
// MessageId: SACDRV_132
//
#define SACDRV_132  0x84

//
// MessageId: SACDRV_133
//
#define SACDRV_133  0x85

//
// MessageId: SACDRV_134
//
#define SACDRV_134  0x86

//
// MessageId: SACDRV_135
//
#define SACDRV_135  0x87

//
// MessageId: SACDRV_136
//
#define SACDRV_136  0x88

//
// MessageId: SACDRV_137
//
#define SACDRV_137  0x89

//
// MessageId: SAC_CHANNEL_NAME
//
#define SAC_CHANNEL_NAME  0x90

//
// MessageId: SAC_CHANNEL_DESCRIPTION
//
#define SAC_CHANNEL_DESCRIPTION  0x91

//
// MessageId: SACDRV_146
//
#define SACDRV_146  0x92

//
// MessageId: SACDRV_147
//
#define SACDRV_147  0x93

//
// MessageId: SACDRV_148
//
#define SACDRV_148  0x94

//
// MessageId: SACDRV_149
//
#define SACDRV_149  0x95

//
// MessageId: SACDRV_150
//
#define SACDRV_150  0x96

//
// MessageId: SACDRV_151
//
#define SACDRV_151  0x97

//
// MessageId: SACDRV_152
//
#define SACDRV_152  0x98

//
// MessageId: SAC_UNINITIALIZED_MSG
//
#define SAC_UNINITIALIZED_MSG  0x99

//
// MessageId: SACDRV_154
//
#define SACDRV_154  0x9a

