/* This file is autogenerated, do not edit. */

#include <stubs.h>

int LoadAlterBitmap()
{
	DbgPrint("WARNING: calling stub LoadAlterBitmap()\n");
	__wine_spec_unimplemented_stub("comdlg32.dll", __FUNCTION__);
	return 0;
}

int WantArrows()
{
	DbgPrint("WARNING: calling stub WantArrows()\n");
	__wine_spec_unimplemented_stub("comdlg32.dll", __FUNCTION__);
	return 0;
}

int dwLBSubclass()
{
	DbgPrint("WARNING: calling stub dwLBSubclass()\n");
	__wine_spec_unimplemented_stub("comdlg32.dll", __FUNCTION__);
	return 0;
}

int dwOKSubclass()
{
	DbgPrint("WARNING: calling stub dwOKSubclass()\n");
	__wine_spec_unimplemented_stub("comdlg32.dll", __FUNCTION__);
	return 0;
}

