/* This file is autogenerated, do not edit. */

#include <stubs.h>

int stub_function2()
{
	DbgPrint("WARNING: calling stub ??0Iostream_init@@QAE@AAVios@@H@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function3()
{
	DbgPrint("WARNING: calling stub ??0Iostream_init@@QAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function4()
{
	DbgPrint("WARNING: calling stub ??0filebuf@@QAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function5()
{
	DbgPrint("WARNING: calling stub ??0filebuf@@QAE@H@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function6()
{
	DbgPrint("WARNING: calling stub ??0filebuf@@QAE@HPADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function7()
{
	DbgPrint("WARNING: calling stub ??0filebuf@@QAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function8()
{
	DbgPrint("WARNING: calling stub ??0fstream@@QAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function9()
{
	DbgPrint("WARNING: calling stub ??0fstream@@QAE@H@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function10()
{
	DbgPrint("WARNING: calling stub ??0fstream@@QAE@HPADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function11()
{
	DbgPrint("WARNING: calling stub ??0fstream@@QAE@PBDHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function12()
{
	DbgPrint("WARNING: calling stub ??0fstream@@QAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function13()
{
	DbgPrint("WARNING: calling stub ??0ifstream@@QAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function14()
{
	DbgPrint("WARNING: calling stub ??0ifstream@@QAE@H@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function15()
{
	DbgPrint("WARNING: calling stub ??0ifstream@@QAE@HPADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function16()
{
	DbgPrint("WARNING: calling stub ??0ifstream@@QAE@PBDHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function17()
{
	DbgPrint("WARNING: calling stub ??0ifstream@@QAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function18()
{
	DbgPrint("WARNING: calling stub ??0ios@@IAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function19()
{
	DbgPrint("WARNING: calling stub ??0ios@@IAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function20()
{
	DbgPrint("WARNING: calling stub ??0ios@@QAE@PAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function21()
{
	DbgPrint("WARNING: calling stub ??0iostream@@IAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function22()
{
	DbgPrint("WARNING: calling stub ??0iostream@@IAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function23()
{
	DbgPrint("WARNING: calling stub ??0iostream@@QAE@PAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function24()
{
	DbgPrint("WARNING: calling stub ??0istream@@IAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function25()
{
	DbgPrint("WARNING: calling stub ??0istream@@IAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function26()
{
	DbgPrint("WARNING: calling stub ??0istream@@QAE@PAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function27()
{
	DbgPrint("WARNING: calling stub ??0istream_withassign@@QAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function28()
{
	DbgPrint("WARNING: calling stub ??0istream_withassign@@QAE@PAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function29()
{
	DbgPrint("WARNING: calling stub ??0istream_withassign@@QAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function30()
{
	DbgPrint("WARNING: calling stub ??0istrstream@@QAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function31()
{
	DbgPrint("WARNING: calling stub ??0istrstream@@QAE@PAD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function32()
{
	DbgPrint("WARNING: calling stub ??0istrstream@@QAE@PADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function33()
{
	DbgPrint("WARNING: calling stub ??0ofstream@@QAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function34()
{
	DbgPrint("WARNING: calling stub ??0ofstream@@QAE@H@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function35()
{
	DbgPrint("WARNING: calling stub ??0ofstream@@QAE@HPADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function36()
{
	DbgPrint("WARNING: calling stub ??0ofstream@@QAE@PBDHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function37()
{
	DbgPrint("WARNING: calling stub ??0ofstream@@QAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function38()
{
	DbgPrint("WARNING: calling stub ??0ostream@@IAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function39()
{
	DbgPrint("WARNING: calling stub ??0ostream@@IAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function40()
{
	DbgPrint("WARNING: calling stub ??0ostream@@QAE@PAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function41()
{
	DbgPrint("WARNING: calling stub ??0ostream_withassign@@QAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function42()
{
	DbgPrint("WARNING: calling stub ??0ostream_withassign@@QAE@PAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function43()
{
	DbgPrint("WARNING: calling stub ??0ostream_withassign@@QAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function44()
{
	DbgPrint("WARNING: calling stub ??0ostrstream@@QAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function45()
{
	DbgPrint("WARNING: calling stub ??0ostrstream@@QAE@PADHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function46()
{
	DbgPrint("WARNING: calling stub ??0ostrstream@@QAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function47()
{
	DbgPrint("WARNING: calling stub ??0stdiobuf@@QAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function48()
{
	DbgPrint("WARNING: calling stub ??0stdiobuf@@QAE@PAU_iobuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function49()
{
	DbgPrint("WARNING: calling stub ??0stdiostream@@QAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function50()
{
	DbgPrint("WARNING: calling stub ??0stdiostream@@QAE@PAU_iobuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function51()
{
	DbgPrint("WARNING: calling stub ??0streambuf@@IAE@PADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function52()
{
	DbgPrint("WARNING: calling stub ??0streambuf@@IAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function53()
{
	DbgPrint("WARNING: calling stub ??0streambuf@@QAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function54()
{
	DbgPrint("WARNING: calling stub ??0strstream@@QAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function55()
{
	DbgPrint("WARNING: calling stub ??0strstream@@QAE@PADHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function56()
{
	DbgPrint("WARNING: calling stub ??0strstream@@QAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function57()
{
	DbgPrint("WARNING: calling stub ??0strstreambuf@@QAE@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function58()
{
	DbgPrint("WARNING: calling stub ??0strstreambuf@@QAE@H@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function59()
{
	DbgPrint("WARNING: calling stub ??0strstreambuf@@QAE@P6APAXJ@ZP6AXPAX@Z@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function60()
{
	DbgPrint("WARNING: calling stub ??0strstreambuf@@QAE@PADH0@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function61()
{
	DbgPrint("WARNING: calling stub ??0strstreambuf@@QAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function62()
{
	DbgPrint("WARNING: calling stub ??1Iostream_init@@QAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function63()
{
	DbgPrint("WARNING: calling stub ??1filebuf@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function64()
{
	DbgPrint("WARNING: calling stub ??1fstream@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function65()
{
	DbgPrint("WARNING: calling stub ??1ifstream@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function66()
{
	DbgPrint("WARNING: calling stub ??1ios@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function67()
{
	DbgPrint("WARNING: calling stub ??1iostream@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function68()
{
	DbgPrint("WARNING: calling stub ??1istream@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function69()
{
	DbgPrint("WARNING: calling stub ??1istream_withassign@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function70()
{
	DbgPrint("WARNING: calling stub ??1istrstream@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function71()
{
	DbgPrint("WARNING: calling stub ??1ofstream@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function72()
{
	DbgPrint("WARNING: calling stub ??1ostream@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function73()
{
	DbgPrint("WARNING: calling stub ??1ostream_withassign@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function74()
{
	DbgPrint("WARNING: calling stub ??1ostrstream@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function75()
{
	DbgPrint("WARNING: calling stub ??1stdiobuf@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function76()
{
	DbgPrint("WARNING: calling stub ??1stdiostream@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function77()
{
	DbgPrint("WARNING: calling stub ??1streambuf@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function78()
{
	DbgPrint("WARNING: calling stub ??1strstream@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function79()
{
	DbgPrint("WARNING: calling stub ??1strstreambuf@@UAE@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function84()
{
	DbgPrint("WARNING: calling stub ??4Iostream_init@@QAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function85()
{
	DbgPrint("WARNING: calling stub ??4filebuf@@QAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function86()
{
	DbgPrint("WARNING: calling stub ??4fstream@@QAEAAV0@AAV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function87()
{
	DbgPrint("WARNING: calling stub ??4ifstream@@QAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function88()
{
	DbgPrint("WARNING: calling stub ??4ios@@IAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function89()
{
	DbgPrint("WARNING: calling stub ??4iostream@@IAEAAV0@AAV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function90()
{
	DbgPrint("WARNING: calling stub ??4iostream@@IAEAAV0@PAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function91()
{
	DbgPrint("WARNING: calling stub ??4istream@@IAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function92()
{
	DbgPrint("WARNING: calling stub ??4istream@@IAEAAV0@PAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function93()
{
	DbgPrint("WARNING: calling stub ??4istream_withassign@@QAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function94()
{
	DbgPrint("WARNING: calling stub ??4istream_withassign@@QAEAAVistream@@ABV1@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function95()
{
	DbgPrint("WARNING: calling stub ??4istream_withassign@@QAEAAVistream@@PAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function96()
{
	DbgPrint("WARNING: calling stub ??4istrstream@@QAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function97()
{
	DbgPrint("WARNING: calling stub ??4ofstream@@QAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function98()
{
	DbgPrint("WARNING: calling stub ??4ostream@@IAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function99()
{
	DbgPrint("WARNING: calling stub ??4ostream@@IAEAAV0@PAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function100()
{
	DbgPrint("WARNING: calling stub ??4ostream_withassign@@QAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function101()
{
	DbgPrint("WARNING: calling stub ??4ostream_withassign@@QAEAAVostream@@ABV1@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function102()
{
	DbgPrint("WARNING: calling stub ??4ostream_withassign@@QAEAAVostream@@PAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function103()
{
	DbgPrint("WARNING: calling stub ??4ostrstream@@QAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function104()
{
	DbgPrint("WARNING: calling stub ??4stdiobuf@@QAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function105()
{
	DbgPrint("WARNING: calling stub ??4stdiostream@@QAEAAV0@AAV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function106()
{
	DbgPrint("WARNING: calling stub ??4streambuf@@QAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function107()
{
	DbgPrint("WARNING: calling stub ??4strstream@@QAEAAV0@AAV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function108()
{
	DbgPrint("WARNING: calling stub ??4strstreambuf@@QAEAAV0@ABV0@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function109()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@AAC@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function110()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@AAD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function111()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@AAE@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function112()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@AAF@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function113()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@AAG@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function114()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@AAH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function115()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@AAI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function116()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@AAJ@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function117()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@AAK@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function118()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@AAM@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function119()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@AAN@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function120()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@AAO@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function121()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@P6AAAV0@AAV0@@Z@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function122()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@P6AAAVios@@AAV1@@Z@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function123()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@PAC@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function124()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@PAD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function125()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@PAE@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function126()
{
	DbgPrint("WARNING: calling stub ??5istream@@QAEAAV0@PAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function127()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@C@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function128()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@D@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function129()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@E@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function130()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@F@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function131()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@G@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function132()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@H@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function133()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@I@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function134()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@J@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function135()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@K@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function136()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@M@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function137()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@N@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function138()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@O@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function139()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@P6AAAV0@AAV0@@Z@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function140()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@P6AAAVios@@AAV1@@Z@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function141()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@PAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function142()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@PBC@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function143()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@PBD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function144()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@PBE@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function145()
{
	DbgPrint("WARNING: calling stub ??6ostream@@QAEAAV0@PBX@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function146()
{
	DbgPrint("WARNING: calling stub ??7ios@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function147()
{
	DbgPrint("WARNING: calling stub ??Bios@@QBEPAXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function148()
{
	DbgPrint("WARNING: calling stub ??_7filebuf@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function149()
{
	DbgPrint("WARNING: calling stub ??_7fstream@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function150()
{
	DbgPrint("WARNING: calling stub ??_7ifstream@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function151()
{
	DbgPrint("WARNING: calling stub ??_7ios@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function152()
{
	DbgPrint("WARNING: calling stub ??_7iostream@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function153()
{
	DbgPrint("WARNING: calling stub ??_7istream@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function154()
{
	DbgPrint("WARNING: calling stub ??_7istream_withassign@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function155()
{
	DbgPrint("WARNING: calling stub ??_7istrstream@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function156()
{
	DbgPrint("WARNING: calling stub ??_7ofstream@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function157()
{
	DbgPrint("WARNING: calling stub ??_7ostream@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function158()
{
	DbgPrint("WARNING: calling stub ??_7ostream_withassign@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function159()
{
	DbgPrint("WARNING: calling stub ??_7ostrstream@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function160()
{
	DbgPrint("WARNING: calling stub ??_7stdiobuf@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function161()
{
	DbgPrint("WARNING: calling stub ??_7stdiostream@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function162()
{
	DbgPrint("WARNING: calling stub ??_7streambuf@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function163()
{
	DbgPrint("WARNING: calling stub ??_7strstream@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function164()
{
	DbgPrint("WARNING: calling stub ??_7strstreambuf@@6B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function165()
{
	DbgPrint("WARNING: calling stub ??_8fstream@@7Bistream@@@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function166()
{
	DbgPrint("WARNING: calling stub ??_8fstream@@7Bostream@@@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function167()
{
	DbgPrint("WARNING: calling stub ??_8ifstream@@7B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function168()
{
	DbgPrint("WARNING: calling stub ??_8iostream@@7Bistream@@@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function169()
{
	DbgPrint("WARNING: calling stub ??_8iostream@@7Bostream@@@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function170()
{
	DbgPrint("WARNING: calling stub ??_8istream@@7B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function171()
{
	DbgPrint("WARNING: calling stub ??_8istream_withassign@@7B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function172()
{
	DbgPrint("WARNING: calling stub ??_8istrstream@@7B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function173()
{
	DbgPrint("WARNING: calling stub ??_8ofstream@@7B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function174()
{
	DbgPrint("WARNING: calling stub ??_8ostream@@7B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function175()
{
	DbgPrint("WARNING: calling stub ??_8ostream_withassign@@7B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function176()
{
	DbgPrint("WARNING: calling stub ??_8ostrstream@@7B@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function177()
{
	DbgPrint("WARNING: calling stub ??_8stdiostream@@7Bistream@@@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function178()
{
	DbgPrint("WARNING: calling stub ??_8stdiostream@@7Bostream@@@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function179()
{
	DbgPrint("WARNING: calling stub ??_8strstream@@7Bistream@@@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function180()
{
	DbgPrint("WARNING: calling stub ??_8strstream@@7Bostream@@@()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function181()
{
	DbgPrint("WARNING: calling stub ??_Dfstream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function182()
{
	DbgPrint("WARNING: calling stub ??_Difstream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function183()
{
	DbgPrint("WARNING: calling stub ??_Diostream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function184()
{
	DbgPrint("WARNING: calling stub ??_Distream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function185()
{
	DbgPrint("WARNING: calling stub ??_Distream_withassign@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function186()
{
	DbgPrint("WARNING: calling stub ??_Distrstream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function187()
{
	DbgPrint("WARNING: calling stub ??_Dofstream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function188()
{
	DbgPrint("WARNING: calling stub ??_Dostream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function189()
{
	DbgPrint("WARNING: calling stub ??_Dostream_withassign@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function190()
{
	DbgPrint("WARNING: calling stub ??_Dostrstream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function191()
{
	DbgPrint("WARNING: calling stub ??_Dstdiostream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function192()
{
	DbgPrint("WARNING: calling stub ??_Dstrstream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function193()
{
	DbgPrint("WARNING: calling stub ??_EIostream_init@@QAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function194()
{
	DbgPrint("WARNING: calling stub ??_Efilebuf@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function195()
{
	DbgPrint("WARNING: calling stub ??_Efstream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function196()
{
	DbgPrint("WARNING: calling stub ??_Eifstream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function197()
{
	DbgPrint("WARNING: calling stub ??_Eios@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function198()
{
	DbgPrint("WARNING: calling stub ??_Eiostream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function199()
{
	DbgPrint("WARNING: calling stub ??_Eistream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function200()
{
	DbgPrint("WARNING: calling stub ??_Eistream_withassign@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function201()
{
	DbgPrint("WARNING: calling stub ??_Eistrstream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function202()
{
	DbgPrint("WARNING: calling stub ??_Eofstream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function203()
{
	DbgPrint("WARNING: calling stub ??_Eostream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function204()
{
	DbgPrint("WARNING: calling stub ??_Eostream_withassign@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function205()
{
	DbgPrint("WARNING: calling stub ??_Eostrstream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function206()
{
	DbgPrint("WARNING: calling stub ??_Estdiobuf@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function207()
{
	DbgPrint("WARNING: calling stub ??_Estdiostream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function208()
{
	DbgPrint("WARNING: calling stub ??_Estreambuf@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function209()
{
	DbgPrint("WARNING: calling stub ??_Estrstream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function210()
{
	DbgPrint("WARNING: calling stub ??_Estrstreambuf@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function211()
{
	DbgPrint("WARNING: calling stub ??_GIostream_init@@QAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function212()
{
	DbgPrint("WARNING: calling stub ??_Gfilebuf@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function213()
{
	DbgPrint("WARNING: calling stub ??_Gfstream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function214()
{
	DbgPrint("WARNING: calling stub ??_Gifstream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function215()
{
	DbgPrint("WARNING: calling stub ??_Gios@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function216()
{
	DbgPrint("WARNING: calling stub ??_Giostream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function217()
{
	DbgPrint("WARNING: calling stub ??_Gistream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function218()
{
	DbgPrint("WARNING: calling stub ??_Gistream_withassign@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function219()
{
	DbgPrint("WARNING: calling stub ??_Gistrstream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function220()
{
	DbgPrint("WARNING: calling stub ??_Gofstream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function221()
{
	DbgPrint("WARNING: calling stub ??_Gostream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function222()
{
	DbgPrint("WARNING: calling stub ??_Gostream_withassign@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function223()
{
	DbgPrint("WARNING: calling stub ??_Gostrstream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function224()
{
	DbgPrint("WARNING: calling stub ??_Gstdiobuf@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function225()
{
	DbgPrint("WARNING: calling stub ??_Gstdiostream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function226()
{
	DbgPrint("WARNING: calling stub ??_Gstreambuf@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function227()
{
	DbgPrint("WARNING: calling stub ??_Gstrstream@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function228()
{
	DbgPrint("WARNING: calling stub ??_Gstrstreambuf@@UAEPAXI@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function234()
{
	DbgPrint("WARNING: calling stub ?adjustfield@ios@@2JB()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function235()
{
	DbgPrint("WARNING: calling stub ?allocate@streambuf@@IAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function236()
{
	DbgPrint("WARNING: calling stub ?attach@filebuf@@QAEPAV1@H@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function237()
{
	DbgPrint("WARNING: calling stub ?attach@fstream@@QAEXH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function238()
{
	DbgPrint("WARNING: calling stub ?attach@ifstream@@QAEXH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function239()
{
	DbgPrint("WARNING: calling stub ?attach@ofstream@@QAEXH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function240()
{
	DbgPrint("WARNING: calling stub ?bad@ios@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function241()
{
	DbgPrint("WARNING: calling stub ?base@streambuf@@IBEPADXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function242()
{
	DbgPrint("WARNING: calling stub ?basefield@ios@@2JB()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function243()
{
	DbgPrint("WARNING: calling stub ?binary@filebuf@@2HB()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function244()
{
	DbgPrint("WARNING: calling stub ?bitalloc@ios@@SAJXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function245()
{
	DbgPrint("WARNING: calling stub ?blen@streambuf@@IBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function246()
{
	DbgPrint("WARNING: calling stub ?cerr@@3Vostream_withassign@@A()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function247()
{
	DbgPrint("WARNING: calling stub ?cin@@3Vistream_withassign@@A()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function248()
{
	DbgPrint("WARNING: calling stub ?clear@ios@@QAEXH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function249()
{
	DbgPrint("WARNING: calling stub ?clog@@3Vostream_withassign@@A()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function250()
{
	DbgPrint("WARNING: calling stub ?close@filebuf@@QAEPAV1@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function251()
{
	DbgPrint("WARNING: calling stub ?close@fstream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function252()
{
	DbgPrint("WARNING: calling stub ?close@ifstream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function253()
{
	DbgPrint("WARNING: calling stub ?close@ofstream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function254()
{
	DbgPrint("WARNING: calling stub ?clrlock@ios@@QAAXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function255()
{
	DbgPrint("WARNING: calling stub ?clrlock@streambuf@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function256()
{
	DbgPrint("WARNING: calling stub ?cout@@3Vostream_withassign@@A()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function257()
{
	DbgPrint("WARNING: calling stub ?dbp@streambuf@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function258()
{
	DbgPrint("WARNING: calling stub ?dec@@YAAAVios@@AAV1@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function259()
{
	DbgPrint("WARNING: calling stub ?delbuf@ios@@QAEXH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function260()
{
	DbgPrint("WARNING: calling stub ?delbuf@ios@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function261()
{
	DbgPrint("WARNING: calling stub ?doallocate@streambuf@@MAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function262()
{
	DbgPrint("WARNING: calling stub ?doallocate@strstreambuf@@MAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function263()
{
	DbgPrint("WARNING: calling stub ?eatwhite@istream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function264()
{
	DbgPrint("WARNING: calling stub ?eback@streambuf@@IBEPADXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function265()
{
	DbgPrint("WARNING: calling stub ?ebuf@streambuf@@IBEPADXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function266()
{
	DbgPrint("WARNING: calling stub ?egptr@streambuf@@IBEPADXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function267()
{
	DbgPrint("WARNING: calling stub ?endl@@YAAAVostream@@AAV1@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function268()
{
	DbgPrint("WARNING: calling stub ?ends@@YAAAVostream@@AAV1@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function269()
{
	DbgPrint("WARNING: calling stub ?eof@ios@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function270()
{
	DbgPrint("WARNING: calling stub ?epptr@streambuf@@IBEPADXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function271()
{
	DbgPrint("WARNING: calling stub ?fLockcInit@ios@@0HA()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function272()
{
	DbgPrint("WARNING: calling stub ?fail@ios@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function273()
{
	DbgPrint("WARNING: calling stub ?fd@filebuf@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function274()
{
	DbgPrint("WARNING: calling stub ?fd@fstream@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function275()
{
	DbgPrint("WARNING: calling stub ?fd@ifstream@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function276()
{
	DbgPrint("WARNING: calling stub ?fd@ofstream@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function277()
{
	DbgPrint("WARNING: calling stub ?fill@ios@@QAEDD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function278()
{
	DbgPrint("WARNING: calling stub ?fill@ios@@QBEDXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function279()
{
	DbgPrint("WARNING: calling stub ?flags@ios@@QAEJJ@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function280()
{
	DbgPrint("WARNING: calling stub ?flags@ios@@QBEJXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function281()
{
	DbgPrint("WARNING: calling stub ?floatfield@ios@@2JB()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function282()
{
	DbgPrint("WARNING: calling stub ?flush@@YAAAVostream@@AAV1@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function283()
{
	DbgPrint("WARNING: calling stub ?flush@ostream@@QAEAAV1@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function284()
{
	DbgPrint("WARNING: calling stub ?freeze@strstreambuf@@QAEXH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function285()
{
	DbgPrint("WARNING: calling stub ?gbump@streambuf@@IAEXH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function286()
{
	DbgPrint("WARNING: calling stub ?gcount@istream@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function287()
{
	DbgPrint("WARNING: calling stub ?get@istream@@QAEAAV1@AAC@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function288()
{
	DbgPrint("WARNING: calling stub ?get@istream@@QAEAAV1@AAD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function289()
{
	DbgPrint("WARNING: calling stub ?get@istream@@QAEAAV1@AAE@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function290()
{
	DbgPrint("WARNING: calling stub ?get@istream@@QAEAAV1@AAVstreambuf@@D@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function291()
{
	DbgPrint("WARNING: calling stub ?get@istream@@QAEAAV1@PACHD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function292()
{
	DbgPrint("WARNING: calling stub ?get@istream@@QAEAAV1@PADHD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function293()
{
	DbgPrint("WARNING: calling stub ?get@istream@@QAEAAV1@PAEHD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function294()
{
	DbgPrint("WARNING: calling stub ?get@istream@@QAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function295()
{
	DbgPrint("WARNING: calling stub ?getdouble@istream@@AAEHPADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function296()
{
	DbgPrint("WARNING: calling stub ?getint@istream@@AAEHPAD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function297()
{
	DbgPrint("WARNING: calling stub ?getline@istream@@QAEAAV1@PACHD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function298()
{
	DbgPrint("WARNING: calling stub ?getline@istream@@QAEAAV1@PADHD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function299()
{
	DbgPrint("WARNING: calling stub ?getline@istream@@QAEAAV1@PAEHD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function300()
{
	DbgPrint("WARNING: calling stub ?good@ios@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function301()
{
	DbgPrint("WARNING: calling stub ?gptr@streambuf@@IBEPADXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function302()
{
	DbgPrint("WARNING: calling stub ?hex@@YAAAVios@@AAV1@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function303()
{
	DbgPrint("WARNING: calling stub ?ignore@istream@@QAEAAV1@HH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function304()
{
	DbgPrint("WARNING: calling stub ?in_avail@streambuf@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function305()
{
	DbgPrint("WARNING: calling stub ?init@ios@@IAEXPAVstreambuf@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function306()
{
	DbgPrint("WARNING: calling stub ?ipfx@istream@@QAEHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function307()
{
	DbgPrint("WARNING: calling stub ?is_open@filebuf@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function308()
{
	DbgPrint("WARNING: calling stub ?is_open@fstream@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function309()
{
	DbgPrint("WARNING: calling stub ?is_open@ifstream@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function310()
{
	DbgPrint("WARNING: calling stub ?is_open@ofstream@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function311()
{
	DbgPrint("WARNING: calling stub ?isfx@istream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function312()
{
	DbgPrint("WARNING: calling stub ?iword@ios@@QBEAAJH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function313()
{
	DbgPrint("WARNING: calling stub ?lock@ios@@QAAXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function314()
{
	DbgPrint("WARNING: calling stub ?lock@streambuf@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function315()
{
	DbgPrint("WARNING: calling stub ?lockbuf@ios@@QAAXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function316()
{
	DbgPrint("WARNING: calling stub ?lockc@ios@@KAXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function317()
{
	DbgPrint("WARNING: calling stub ?lockptr@ios@@IAEPAU_RTL_CRITICAL_SECTION@@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function318()
{
	DbgPrint("WARNING: calling stub ?lockptr@streambuf@@IAEPAU_RTL_CRITICAL_SECTION@@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function319()
{
	DbgPrint("WARNING: calling stub ?oct@@YAAAVios@@AAV1@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function320()
{
	DbgPrint("WARNING: calling stub ?open@filebuf@@QAEPAV1@PBDHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function321()
{
	DbgPrint("WARNING: calling stub ?open@fstream@@QAEXPBDHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function322()
{
	DbgPrint("WARNING: calling stub ?open@ifstream@@QAEXPBDHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function323()
{
	DbgPrint("WARNING: calling stub ?open@ofstream@@QAEXPBDHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function324()
{
	DbgPrint("WARNING: calling stub ?openprot@filebuf@@2HB()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function325()
{
	DbgPrint("WARNING: calling stub ?opfx@ostream@@QAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function326()
{
	DbgPrint("WARNING: calling stub ?osfx@ostream@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function327()
{
	DbgPrint("WARNING: calling stub ?out_waiting@streambuf@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function328()
{
	DbgPrint("WARNING: calling stub ?overflow@filebuf@@UAEHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function329()
{
	DbgPrint("WARNING: calling stub ?overflow@stdiobuf@@UAEHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function330()
{
	DbgPrint("WARNING: calling stub ?overflow@strstreambuf@@UAEHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function331()
{
	DbgPrint("WARNING: calling stub ?pbackfail@stdiobuf@@UAEHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function332()
{
	DbgPrint("WARNING: calling stub ?pbackfail@streambuf@@UAEHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function333()
{
	DbgPrint("WARNING: calling stub ?pbase@streambuf@@IBEPADXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function334()
{
	DbgPrint("WARNING: calling stub ?pbump@streambuf@@IAEXH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function335()
{
	DbgPrint("WARNING: calling stub ?pcount@ostrstream@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function336()
{
	DbgPrint("WARNING: calling stub ?pcount@strstream@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function337()
{
	DbgPrint("WARNING: calling stub ?peek@istream@@QAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function338()
{
	DbgPrint("WARNING: calling stub ?pptr@streambuf@@IBEPADXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function339()
{
	DbgPrint("WARNING: calling stub ?precision@ios@@QAEHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function340()
{
	DbgPrint("WARNING: calling stub ?precision@ios@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function341()
{
	DbgPrint("WARNING: calling stub ?put@ostream@@QAEAAV1@C@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function342()
{
	DbgPrint("WARNING: calling stub ?put@ostream@@QAEAAV1@D@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function343()
{
	DbgPrint("WARNING: calling stub ?put@ostream@@QAEAAV1@E@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function344()
{
	DbgPrint("WARNING: calling stub ?putback@istream@@QAEAAV1@D@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function345()
{
	DbgPrint("WARNING: calling stub ?pword@ios@@QBEAAPAXH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function346()
{
	DbgPrint("WARNING: calling stub ?rdbuf@fstream@@QBEPAVfilebuf@@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function347()
{
	DbgPrint("WARNING: calling stub ?rdbuf@ifstream@@QBEPAVfilebuf@@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function348()
{
	DbgPrint("WARNING: calling stub ?rdbuf@ios@@QBEPAVstreambuf@@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function349()
{
	DbgPrint("WARNING: calling stub ?rdbuf@istrstream@@QBEPAVstrstreambuf@@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function350()
{
	DbgPrint("WARNING: calling stub ?rdbuf@ofstream@@QBEPAVfilebuf@@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function351()
{
	DbgPrint("WARNING: calling stub ?rdbuf@ostrstream@@QBEPAVstrstreambuf@@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function352()
{
	DbgPrint("WARNING: calling stub ?rdbuf@stdiostream@@QBEPAVstdiobuf@@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function353()
{
	DbgPrint("WARNING: calling stub ?rdbuf@strstream@@QBEPAVstrstreambuf@@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function354()
{
	DbgPrint("WARNING: calling stub ?rdstate@ios@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function355()
{
	DbgPrint("WARNING: calling stub ?read@istream@@QAEAAV1@PACH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function356()
{
	DbgPrint("WARNING: calling stub ?read@istream@@QAEAAV1@PADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function357()
{
	DbgPrint("WARNING: calling stub ?read@istream@@QAEAAV1@PAEH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function358()
{
	DbgPrint("WARNING: calling stub ?sbumpc@streambuf@@QAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function359()
{
	DbgPrint("WARNING: calling stub ?seekg@istream@@QAEAAV1@J@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function360()
{
	DbgPrint("WARNING: calling stub ?seekg@istream@@QAEAAV1@JW4seek_dir@ios@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function361()
{
	DbgPrint("WARNING: calling stub ?seekoff@filebuf@@UAEJJW4seek_dir@ios@@H@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function362()
{
	DbgPrint("WARNING: calling stub ?seekoff@stdiobuf@@UAEJJW4seek_dir@ios@@H@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function363()
{
	DbgPrint("WARNING: calling stub ?seekoff@streambuf@@UAEJJW4seek_dir@ios@@H@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function364()
{
	DbgPrint("WARNING: calling stub ?seekoff@strstreambuf@@UAEJJW4seek_dir@ios@@H@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function365()
{
	DbgPrint("WARNING: calling stub ?seekp@ostream@@QAEAAV1@J@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function366()
{
	DbgPrint("WARNING: calling stub ?seekp@ostream@@QAEAAV1@JW4seek_dir@ios@@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function367()
{
	DbgPrint("WARNING: calling stub ?seekpos@streambuf@@UAEJJH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function370()
{
	DbgPrint("WARNING: calling stub ?setb@streambuf@@IAEXPAD0H@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function371()
{
	DbgPrint("WARNING: calling stub ?setbuf@filebuf@@UAEPAVstreambuf@@PADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function372()
{
	DbgPrint("WARNING: calling stub ?setbuf@fstream@@QAEPAVstreambuf@@PADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function373()
{
	DbgPrint("WARNING: calling stub ?setbuf@ifstream@@QAEPAVstreambuf@@PADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function374()
{
	DbgPrint("WARNING: calling stub ?setbuf@ofstream@@QAEPAVstreambuf@@PADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function375()
{
	DbgPrint("WARNING: calling stub ?setbuf@streambuf@@UAEPAV1@PADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function376()
{
	DbgPrint("WARNING: calling stub ?setbuf@strstreambuf@@UAEPAVstreambuf@@PADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function377()
{
	DbgPrint("WARNING: calling stub ?setf@ios@@QAEJJ@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function378()
{
	DbgPrint("WARNING: calling stub ?setf@ios@@QAEJJJ@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function379()
{
	DbgPrint("WARNING: calling stub ?setg@streambuf@@IAEXPAD00@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function380()
{
	DbgPrint("WARNING: calling stub ?setlock@ios@@QAAXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function381()
{
	DbgPrint("WARNING: calling stub ?setlock@streambuf@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function382()
{
	DbgPrint("WARNING: calling stub ?setmode@filebuf@@QAEHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function383()
{
	DbgPrint("WARNING: calling stub ?setmode@fstream@@QAEHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function384()
{
	DbgPrint("WARNING: calling stub ?setmode@ifstream@@QAEHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function385()
{
	DbgPrint("WARNING: calling stub ?setmode@ofstream@@QAEHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function386()
{
	DbgPrint("WARNING: calling stub ?setp@streambuf@@IAEXPAD0@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function387()
{
	DbgPrint("WARNING: calling stub ?setrwbuf@stdiobuf@@QAEHHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function388()
{
	DbgPrint("WARNING: calling stub ?sgetc@streambuf@@QAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function389()
{
	DbgPrint("WARNING: calling stub ?sgetn@streambuf@@QAEHPADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function390()
{
	DbgPrint("WARNING: calling stub ?sh_none@filebuf@@2HB()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function391()
{
	DbgPrint("WARNING: calling stub ?sh_read@filebuf@@2HB()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function392()
{
	DbgPrint("WARNING: calling stub ?sh_write@filebuf@@2HB()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function393()
{
	DbgPrint("WARNING: calling stub ?snextc@streambuf@@QAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function394()
{
	DbgPrint("WARNING: calling stub ?sputbackc@streambuf@@QAEHD@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function395()
{
	DbgPrint("WARNING: calling stub ?sputc@streambuf@@QAEHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function396()
{
	DbgPrint("WARNING: calling stub ?sputn@streambuf@@QAEHPBDH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function397()
{
	DbgPrint("WARNING: calling stub ?stdiofile@stdiobuf@@QAEPAU_iobuf@@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function398()
{
	DbgPrint("WARNING: calling stub ?stossc@streambuf@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function399()
{
	DbgPrint("WARNING: calling stub ?str@istrstream@@QAEPADXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function400()
{
	DbgPrint("WARNING: calling stub ?str@ostrstream@@QAEPADXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function401()
{
	DbgPrint("WARNING: calling stub ?str@strstream@@QAEPADXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function402()
{
	DbgPrint("WARNING: calling stub ?str@strstreambuf@@QAEPADXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function403()
{
	DbgPrint("WARNING: calling stub ?sunk_with_stdio@ios@@0HA()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function404()
{
	DbgPrint("WARNING: calling stub ?sync@filebuf@@UAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function405()
{
	DbgPrint("WARNING: calling stub ?sync@istream@@QAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function406()
{
	DbgPrint("WARNING: calling stub ?sync@stdiobuf@@UAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function407()
{
	DbgPrint("WARNING: calling stub ?sync@streambuf@@UAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function408()
{
	DbgPrint("WARNING: calling stub ?sync@strstreambuf@@UAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function409()
{
	DbgPrint("WARNING: calling stub ?sync_with_stdio@ios@@SAXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function410()
{
	DbgPrint("WARNING: calling stub ?tellg@istream@@QAEJXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function411()
{
	DbgPrint("WARNING: calling stub ?tellp@ostream@@QAEJXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function413()
{
	DbgPrint("WARNING: calling stub ?text@filebuf@@2HB()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function414()
{
	DbgPrint("WARNING: calling stub ?tie@ios@@QAEPAVostream@@PAV2@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function415()
{
	DbgPrint("WARNING: calling stub ?tie@ios@@QBEPAVostream@@XZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function416()
{
	DbgPrint("WARNING: calling stub ?unbuffered@streambuf@@IAEXH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function417()
{
	DbgPrint("WARNING: calling stub ?unbuffered@streambuf@@IBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function418()
{
	DbgPrint("WARNING: calling stub ?underflow@filebuf@@UAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function419()
{
	DbgPrint("WARNING: calling stub ?underflow@stdiobuf@@UAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function420()
{
	DbgPrint("WARNING: calling stub ?underflow@strstreambuf@@UAEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function422()
{
	DbgPrint("WARNING: calling stub ?unlock@ios@@QAAXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function423()
{
	DbgPrint("WARNING: calling stub ?unlock@streambuf@@QAEXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function424()
{
	DbgPrint("WARNING: calling stub ?unlockbuf@ios@@QAAXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function425()
{
	DbgPrint("WARNING: calling stub ?unlockc@ios@@KAXXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function426()
{
	DbgPrint("WARNING: calling stub ?unsetf@ios@@QAEJJ@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function427()
{
	DbgPrint("WARNING: calling stub ?width@ios@@QAEHH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function428()
{
	DbgPrint("WARNING: calling stub ?width@ios@@QBEHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function429()
{
	DbgPrint("WARNING: calling stub ?write@ostream@@QAEAAV1@PBCH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function430()
{
	DbgPrint("WARNING: calling stub ?write@ostream@@QAEAAV1@PBDH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function431()
{
	DbgPrint("WARNING: calling stub ?write@ostream@@QAEAAV1@PBEH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function432()
{
	DbgPrint("WARNING: calling stub ?writepad@ostream@@AAEAAV1@PBD0@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function433()
{
	DbgPrint("WARNING: calling stub ?ws@@YAAAVistream@@AAV1@@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function434()
{
	DbgPrint("WARNING: calling stub ?x_curindex@ios@@0HA()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function435()
{
	DbgPrint("WARNING: calling stub ?x_lockc@ios@@0U_RTL_CRITICAL_SECTION@@A()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function436()
{
	DbgPrint("WARNING: calling stub ?x_maxbit@ios@@0JA()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function437()
{
	DbgPrint("WARNING: calling stub ?x_statebuf@ios@@0QAJA()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function438()
{
	DbgPrint("WARNING: calling stub ?xalloc@ios@@SAHXZ()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function439()
{
	DbgPrint("WARNING: calling stub ?xsgetn@streambuf@@UAEHPADH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int stub_function440()
{
	DbgPrint("WARNING: calling stub ?xsputn@streambuf@@UAEHPBDH@Z()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int _mtlock()
{
	DbgPrint("WARNING: calling stub _mtlock()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

int _mtunlock()
{
	DbgPrint("WARNING: calling stub _mtunlock()\n");
	__wine_spec_unimplemented_stub("msvcrt20.dll", __FUNCTION__);
	return 0;
}

