/* This file is autogenerated, do not edit. */

#include <stubs.h>

int SerialDisplayAdvancedSettings()
{
	DbgPrint("WARNING: calling stub SerialDisplayAdvancedSettings()\n");
	__wine_spec_unimplemented_stub("msports.dll", __FUNCTION__);
	return 0;
}

