/*** Autogenerated by WIDL <undefined version> from /home/jens/winos/reactos/sdk/include/psdk/pstore.idl - Do not edit ***/

#ifdef __REACTOS__
#define WIN32_NO_STATUS
#define WIN32_LEAN_AND_MEAN
#endif

#include <rpc.h>
#include <rpcndr.h>

#ifdef _MIDL_USE_GUIDDEF_

#ifndef INITGUID
#define INITGUID
#include <guiddef.h>
#undef INITGUID
#else
#include <guiddef.h>
#endif

#define MIDL_DEFINE_GUID(type,name,l,w1,w2,b1,b2,b3,b4,b5,b6,b7,b8) \
    DEFINE_GUID(name,l,w1,w2,b1,b2,b3,b4,b5,b6,b7,b8)

#else

#define MIDL_DEFINE_GUID(type,name,l,w1,w2,b1,b2,b3,b4,b5,b6,b7,b8) \
    const type name = {l,w1,w2,{b1,b2,b3,b4,b5,b6,b7,b8}}

#endif

#ifdef __cplusplus
extern "C" {
#endif

MIDL_DEFINE_GUID(IID, LIBID_PSTORECLib, 0x5a6f1ebd, 0x2db1, 0x11d0, 0x8c,0x39, 0x00,0xc0,0x4f,0xd9,0x12,0x6b);
MIDL_DEFINE_GUID(IID, IID_IEnumPStoreItems, 0x5a6f1ec1, 0x2db1, 0x11d0, 0x8c,0x39, 0x00,0xc0,0x4f,0xd9,0x12,0x6b);
MIDL_DEFINE_GUID(IID, IID_IEnumPStoreTypes, 0x789c1cbf, 0x31ee, 0x11d0, 0x8c,0x39, 0x00,0xc0,0x4f,0xd9,0x12,0x6b);
MIDL_DEFINE_GUID(IID, IID_IPStore, 0x5a6f1ec0, 0x2db1, 0x11d0, 0x8c,0x39, 0x00,0xc0,0x4f,0xd9,0x12,0x6b);

#ifdef __cplusplus
}
#endif

#undef MIDL_DEFINE_GUID
