/* This file is autogenerated, do not edit. */

#include <stubs.h>

int AtlSetErrorInfo()
{
	DbgPrint("WARNING: calling stub AtlSetErrorInfo()\n");
	__wine_spec_unimplemented_stub("atl.dll", __FUNCTION__);
	return 0;
}

int AtlDevModeW2A()
{
	DbgPrint("WARNING: calling stub AtlDevModeW2A()\n");
	__wine_spec_unimplemented_stub("atl.dll", __FUNCTION__);
	return 0;
}

int AtlModuleUnRegisterTypeLib()
{
	DbgPrint("WARNING: calling stub AtlModuleUnRegisterTypeLib()\n");
	__wine_spec_unimplemented_stub("atl.dll", __FUNCTION__);
	return 0;
}

