/* This file is autogenerated, do not edit. */

#include <stubs.h>

int ClearEventData()
{
	DbgPrint("WARNING: calling stub ClearEventData()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int CreateBlob()
{
	DbgPrint("WARNING: calling stub CreateBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int CreateNPPInterface()
{
	DbgPrint("WARNING: calling stub CreateNPPInterface()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int DestroyBlob()
{
	DbgPrint("WARNING: calling stub DestroyBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int DestroyNPPBlobTable()
{
	DbgPrint("WARNING: calling stub DestroyNPPBlobTable()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int DuplicateBlob()
{
	DbgPrint("WARNING: calling stub DuplicateBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int FilterNPPBlob()
{
	DbgPrint("WARNING: calling stub FilterNPPBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int FindOneOf()
{
	DbgPrint("WARNING: calling stub FindOneOf()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int FindUnknownBlobCategories()
{
	DbgPrint("WARNING: calling stub FindUnknownBlobCategories()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int FindUnknownBlobTags()
{
	DbgPrint("WARNING: calling stub FindUnknownBlobTags()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetBoolFromBlob()
{
	DbgPrint("WARNING: calling stub GetBoolFromBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetClassIDFromBlob()
{
	DbgPrint("WARNING: calling stub GetClassIDFromBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetDwordFromBlob()
{
	DbgPrint("WARNING: calling stub GetDwordFromBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetMacAddressFromBlob()
{
	DbgPrint("WARNING: calling stub GetMacAddressFromBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetNPPAddressFilterFromBlob()
{
	DbgPrint("WARNING: calling stub GetNPPAddressFilterFromBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetNPPBlobFromUI()
{
	DbgPrint("WARNING: calling stub GetNPPBlobFromUI()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetNPPBlobTable()
{
	DbgPrint("WARNING: calling stub GetNPPBlobTable()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetNPPEtypeSapFilter()
{
	DbgPrint("WARNING: calling stub GetNPPEtypeSapFilter()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetNPPMacTypeAsNumber()
{
	DbgPrint("WARNING: calling stub GetNPPMacTypeAsNumber()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetNPPPatternFilterFromBlob()
{
	DbgPrint("WARNING: calling stub GetNPPPatternFilterFromBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetNPPTriggerFromBlob()
{
	DbgPrint("WARNING: calling stub GetNPPTriggerFromBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetNetworkInfoFromBlob()
{
	DbgPrint("WARNING: calling stub GetNetworkInfoFromBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetStringFromBlob()
{
	DbgPrint("WARNING: calling stub GetStringFromBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int GetStringsFromBlob()
{
	DbgPrint("WARNING: calling stub GetStringsFromBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int IsRemoteNPP()
{
	DbgPrint("WARNING: calling stub IsRemoteNPP()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int LockBlob()
{
	DbgPrint("WARNING: calling stub LockBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int MarshalBlob()
{
	DbgPrint("WARNING: calling stub MarshalBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int MergeBlob()
{
	DbgPrint("WARNING: calling stub MergeBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int NmAddUsedEntry()
{
	DbgPrint("WARNING: calling stub NmAddUsedEntry()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int NmHeapAllocate()
{
	DbgPrint("WARNING: calling stub NmHeapAllocate()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int NmHeapFree()
{
	DbgPrint("WARNING: calling stub NmHeapFree()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int NmHeapReallocate()
{
	DbgPrint("WARNING: calling stub NmHeapReallocate()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int NmHeapSetMaxSize()
{
	DbgPrint("WARNING: calling stub NmHeapSetMaxSize()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int NmHeapSize()
{
	DbgPrint("WARNING: calling stub NmHeapSize()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int NmRemoveUsedEntry()
{
	DbgPrint("WARNING: calling stub NmRemoveUsedEntry()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int RaiseNMEvent()
{
	DbgPrint("WARNING: calling stub RaiseNMEvent()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int ReadBlobFromFile()
{
	DbgPrint("WARNING: calling stub ReadBlobFromFile()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int RegCreateBlobKey()
{
	DbgPrint("WARNING: calling stub RegCreateBlobKey()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int RegOpenBlobKey()
{
	DbgPrint("WARNING: calling stub RegOpenBlobKey()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int ReleaseEventSystem()
{
	DbgPrint("WARNING: calling stub ReleaseEventSystem()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int RemoveFromBlob()
{
	DbgPrint("WARNING: calling stub RemoveFromBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int SelectNPPBlobFromTable()
{
	DbgPrint("WARNING: calling stub SelectNPPBlobFromTable()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int SendEvent()
{
	DbgPrint("WARNING: calling stub SendEvent()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int SetBoolInBlob()
{
	DbgPrint("WARNING: calling stub SetBoolInBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int SetClassIDInBlob()
{
	DbgPrint("WARNING: calling stub SetClassIDInBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int SetDwordInBlob()
{
	DbgPrint("WARNING: calling stub SetDwordInBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int SetMacAddressInBlob()
{
	DbgPrint("WARNING: calling stub SetMacAddressInBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int SetNPPAddressFilterInBlob()
{
	DbgPrint("WARNING: calling stub SetNPPAddressFilterInBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int SetNPPEtypeSapFilter()
{
	DbgPrint("WARNING: calling stub SetNPPEtypeSapFilter()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int SetNPPPatternFilterInBlob()
{
	DbgPrint("WARNING: calling stub SetNPPPatternFilterInBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int SetNPPTriggerInBlob()
{
	DbgPrint("WARNING: calling stub SetNPPTriggerInBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int SetNetworkInfoInBlob()
{
	DbgPrint("WARNING: calling stub SetNetworkInfoInBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int SetStringInBlob()
{
	DbgPrint("WARNING: calling stub SetStringInBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int SubkeyExists()
{
	DbgPrint("WARNING: calling stub SubkeyExists()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int UnMarshalBlob()
{
	DbgPrint("WARNING: calling stub UnMarshalBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int UnlockBlob()
{
	DbgPrint("WARNING: calling stub UnlockBlob()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int WriteBlobToFile()
{
	DbgPrint("WARNING: calling stub WriteBlobToFile()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int WriteCrackedBlobToFile()
{
	DbgPrint("WARNING: calling stub WriteCrackedBlobToFile()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int recursiveDeleteKey()
{
	DbgPrint("WARNING: calling stub recursiveDeleteKey()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

int setKeyAndValue()
{
	DbgPrint("WARNING: calling stub setKeyAndValue()\n");
	__wine_spec_unimplemented_stub("npptools.dll", __FUNCTION__);
	return 0;
}

