/* This file is autogenerated, do not edit. */

#include <stubs.h>

int ImageView_COMServer()
{
	DbgPrint("WARNING: calling stub ImageView_COMServer()\n");
	__wine_spec_unimplemented_stub("shimgvw.dll", __FUNCTION__);
	return 0;
}

int ConvertDIBSECTIONToThumbnail()
{
	DbgPrint("WARNING: calling stub ConvertDIBSECTIONToThumbnail()\n");
	__wine_spec_unimplemented_stub("shimgvw.dll", __FUNCTION__);
	return 0;
}

int DllInstall()
{
	DbgPrint("WARNING: calling stub DllInstall()\n");
	__wine_spec_unimplemented_stub("shimgvw.dll", __FUNCTION__);
	return 0;
}

