/* This file is autogenerated, do not edit. */

#include <stubs.h>

int RasAutodialAddressToNetwork()
{
	DbgPrint("WARNING: calling stub RasAutodialAddressToNetwork()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasAutodialEntryToNetwork()
{
	DbgPrint("WARNING: calling stub RasAutodialEntryToNetwork()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasDialWow()
{
	DbgPrint("WARNING: calling stub RasDialWow()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasEnumConnectionsWow()
{
	DbgPrint("WARNING: calling stub RasEnumConnectionsWow()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasEnumEntriesWow()
{
	DbgPrint("WARNING: calling stub RasEnumEntriesWow()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasGetConnectResponse()
{
	DbgPrint("WARNING: calling stub RasGetConnectResponse()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasGetConnectStatusWow()
{
	DbgPrint("WARNING: calling stub RasGetConnectStatusWow()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasGetCountryInfoA()
{
	DbgPrint("WARNING: calling stub RasGetCountryInfoA()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasGetCountryInfoW()
{
	DbgPrint("WARNING: calling stub RasGetCountryInfoW()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasGetCredentialsA()
{
	DbgPrint("WARNING: calling stub RasGetCredentialsA()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasGetCredentialsW()
{
	DbgPrint("WARNING: calling stub RasGetCredentialsW()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasGetErrorStringWow()
{
	DbgPrint("WARNING: calling stub RasGetErrorStringWow()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasGetHport()
{
	DbgPrint("WARNING: calling stub RasGetHport()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasGetSubEntryHandleA()
{
	DbgPrint("WARNING: calling stub RasGetSubEntryHandleA()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasGetSubEntryHandleW()
{
	DbgPrint("WARNING: calling stub RasGetSubEntryHandleW()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasGetSubEntryPropertiesA()
{
	DbgPrint("WARNING: calling stub RasGetSubEntryPropertiesA()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasGetSubEntryPropertiesW()
{
	DbgPrint("WARNING: calling stub RasGetSubEntryPropertiesW()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasHangUpWow()
{
	DbgPrint("WARNING: calling stub RasHangUpWow()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasSetCredentialsA()
{
	DbgPrint("WARNING: calling stub RasSetCredentialsA()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasSetCredentialsW()
{
	DbgPrint("WARNING: calling stub RasSetCredentialsW()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasSetOldPassword()
{
	DbgPrint("WARNING: calling stub RasSetOldPassword()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaEngineRequest()
{
	DbgPrint("WARNING: calling stub RnaEngineRequest()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int DialEngineRequest()
{
	DbgPrint("WARNING: calling stub DialEngineRequest()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int SuprvRequest()
{
	DbgPrint("WARNING: calling stub SuprvRequest()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int DialInMessage()
{
	DbgPrint("WARNING: calling stub DialInMessage()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaEnumConnEntries()
{
	DbgPrint("WARNING: calling stub RnaEnumConnEntries()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaGetConnEntry()
{
	DbgPrint("WARNING: calling stub RnaGetConnEntry()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaFreeConnEntry()
{
	DbgPrint("WARNING: calling stub RnaFreeConnEntry()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaSaveConnEntry()
{
	DbgPrint("WARNING: calling stub RnaSaveConnEntry()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaDeleteConnEntry()
{
	DbgPrint("WARNING: calling stub RnaDeleteConnEntry()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaRenameConnEntry()
{
	DbgPrint("WARNING: calling stub RnaRenameConnEntry()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaValidateEntryName()
{
	DbgPrint("WARNING: calling stub RnaValidateEntryName()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaEnumDevices()
{
	DbgPrint("WARNING: calling stub RnaEnumDevices()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaGetDeviceInfo()
{
	DbgPrint("WARNING: calling stub RnaGetDeviceInfo()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaGetDefaultDevConfig()
{
	DbgPrint("WARNING: calling stub RnaGetDefaultDevConfig()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaBuildDevConfig()
{
	DbgPrint("WARNING: calling stub RnaBuildDevConfig()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaDevConfigDlg()
{
	DbgPrint("WARNING: calling stub RnaDevConfigDlg()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaFreeDevConfig()
{
	DbgPrint("WARNING: calling stub RnaFreeDevConfig()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaActivateEngine()
{
	DbgPrint("WARNING: calling stub RnaActivateEngine()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaDeactivateEngine()
{
	DbgPrint("WARNING: calling stub RnaDeactivateEngine()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int SuprvEnumAccessInfo()
{
	DbgPrint("WARNING: calling stub SuprvEnumAccessInfo()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int SuprvGetAccessInfo()
{
	DbgPrint("WARNING: calling stub SuprvGetAccessInfo()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int SuprvSetAccessInfo()
{
	DbgPrint("WARNING: calling stub SuprvSetAccessInfo()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int SuprvGetAdminConfig()
{
	DbgPrint("WARNING: calling stub SuprvGetAdminConfig()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int SuprvInitialize()
{
	DbgPrint("WARNING: calling stub SuprvInitialize()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int SuprvDeInitialize()
{
	DbgPrint("WARNING: calling stub SuprvDeInitialize()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaUIDial()
{
	DbgPrint("WARNING: calling stub RnaUIDial()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaImplicitDial()
{
	DbgPrint("WARNING: calling stub RnaImplicitDial()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RasDial16()
{
	DbgPrint("WARNING: calling stub RasDial16()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaSMMInfoDialog()
{
	DbgPrint("WARNING: calling stub RnaSMMInfoDialog()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaEnumerateMacNames()
{
	DbgPrint("WARNING: calling stub RnaEnumerateMacNames()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaEnumCountryInfo()
{
	DbgPrint("WARNING: calling stub RnaEnumCountryInfo()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaGetAreaCodeList()
{
	DbgPrint("WARNING: calling stub RnaGetAreaCodeList()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaFindDriver()
{
	DbgPrint("WARNING: calling stub RnaFindDriver()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaInstallDriver()
{
	DbgPrint("WARNING: calling stub RnaInstallDriver()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaGetDialSettings()
{
	DbgPrint("WARNING: calling stub RnaGetDialSettings()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaSetDialSettings()
{
	DbgPrint("WARNING: calling stub RnaSetDialSettings()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaGetIPInfo()
{
	DbgPrint("WARNING: calling stub RnaGetIPInfo()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaSetIPInfo()
{
	DbgPrint("WARNING: calling stub RnaSetIPInfo()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaCloseMac()
{
	DbgPrint("WARNING: calling stub RnaCloseMac()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaComplete()
{
	DbgPrint("WARNING: calling stub RnaComplete()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaGetDevicePort()
{
	DbgPrint("WARNING: calling stub RnaGetDevicePort()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaGetUserProfile()
{
	DbgPrint("WARNING: calling stub RnaGetUserProfile()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaOpenMac()
{
	DbgPrint("WARNING: calling stub RnaOpenMac()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaSessInitialize()
{
	DbgPrint("WARNING: calling stub RnaSessInitialize()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaStartCallback()
{
	DbgPrint("WARNING: calling stub RnaStartCallback()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaTerminate()
{
	DbgPrint("WARNING: calling stub RnaTerminate()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaUICallbackDialog()
{
	DbgPrint("WARNING: calling stub RnaUICallbackDialog()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

int RnaUIUsernamePassword()
{
	DbgPrint("WARNING: calling stub RnaUIUsernamePassword()\n");
	__wine_spec_unimplemented_stub("rasapi32.dll", __FUNCTION__);
	return 0;
}

