/* This file is autogenerated, do not edit. */

#include <stubs.h>

int DeleteServicePlugPlayRegKeys()
{
	DbgPrint("WARNING: calling stub DeleteServicePlugPlayRegKeys()\n");
	__wine_spec_unimplemented_stub("umpnpmgr.dll", __FUNCTION__);
	return 0;
}

int RegisterScmCallback()
{
	DbgPrint("WARNING: calling stub RegisterScmCallback()\n");
	__wine_spec_unimplemented_stub("umpnpmgr.dll", __FUNCTION__);
	return 0;
}

int RegisterServiceNotification()
{
	DbgPrint("WARNING: calling stub RegisterServiceNotification()\n");
	__wine_spec_unimplemented_stub("umpnpmgr.dll", __FUNCTION__);
	return 0;
}

