/* This file is autogenerated, do not edit. */

#include <stubs.h>

int SymGetOmapBlockBase()
{
	DbgPrint("WARNING: calling stub SymGetOmapBlockBase()\n");
	__wine_spec_unimplemented_stub("dbghelp.dll", __FUNCTION__);
	return 0;
}

int SymSetSymWithAddr64()
{
	DbgPrint("WARNING: calling stub SymSetSymWithAddr64()\n");
	__wine_spec_unimplemented_stub("dbghelp.dll", __FUNCTION__);
	return 0;
}

int __stdcall dbghelp(void* a0, void* a1)
{
	DbgPrint("WARNING: calling stub dbghelp(0x%p,0x%p)\n", (void*)a0, (void*)a1);
	return 0;
}

